-- D-002 (docs/decisions/deviations.md): TypeSafe Jev System One is a pinned model. The ledger's model
-- id column is closed over the seam's own roster (`MODEL_IDS`, src/core/model-ledger.types.ts), and
-- that roster gains `jev-latest` — the id every closed question the product asks is now pinned,
-- hashed and billed under. Generated by drizzle-kit from the schema and read: it re-closes ONE check
-- over the three ids and touches nothing else. Every row standing before it names one of the two
-- Claude ids, which the new check still admits, so there is nothing to backfill.
ALTER TABLE "model_calls" DROP CONSTRAINT "model_calls_model_id_closed";--> statement-breakpoint
ALTER TABLE "model_calls" ADD CONSTRAINT "model_calls_model_id_closed" CHECK ("model_calls"."model_id" in ('claude-opus-5', 'claude-sonnet-5', 'jev-latest'));