#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Answer-Key custody (ADR 0026). Run by the owner: ! bash scripts/owner/custody-setup.sh
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=/nonexistent/.env   # this wizard writes no .env values
KEY_USER=vxkeys
KEY_DIR=/home/$KEY_USER/keys
SCORER=/usr/local/bin/vx-score
SCORER_RULE=/etc/sudoers.d/91-vx-score
OLD_RULE=/etc/sudoers.d/90-riz
ME=$(id -un)

banner "Answer-Key custody (ADR 0026)"

stage "Check this machine"
say "This moves every Answer Key to a separate Linux user, and puts a password back on sudo."
say "You are: $ME. Keys user: $KEY_USER. Keys folder: $KEY_DIR."
if sudo -n true 2>/dev/null; then
  note "sudo needs no password right now (that is what we are fixing)."
else
  note "sudo already asks a password; you will type it when asked."
fi
if ! id -nG "$ME" | tr ' ' '\n' | grep -qx sudo; then
  warn "$ME is not in the 'sudo' group. Removing the password-free rule would lock you out of root."
  warn "Stop here and tell Claude. (Recovery from Windows is always: wsl -u root)"
  exit 1
fi
pause "Your user is in the sudo group. Press Enter to continue."

stage "Give your user a password"
say "Your Linux password is currently: $(passwd -S "$ME" | awk '{print ($2=="P") ? "set" : "NOT set (locked)"}')."
say "Once sudo asks a password, you need one. Choose it now (typing is hidden)."
if confirm "Set or change the password for $ME now?"; then
  sudo passwd "$ME"
fi
say "Checking the password works (type it once more):"
if su "$ME" -c true; then
  printf '  %s✓ password works%s\n' "$GREEN" "$RESET"
else
  warn "The password check failed. Stop here: do not remove the password-free rule yet."
  exit 1
fi
pause

stage "Create the keys user"
if id "$KEY_USER" >/dev/null 2>&1; then
  note "$KEY_USER already exists."
else
  sudo adduser --disabled-password --gecos "" "$KEY_USER" >/dev/null
  printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$KEY_USER"
fi
sudo chmod 700 "/home/$KEY_USER"
sudo install -d -o "$KEY_USER" -g "$KEY_USER" -m 700 "$KEY_DIR"
printf '  %s✓%s /home/%s is 700; %s exists\n' "$GREEN" "$RESET" "$KEY_USER" "$KEY_DIR"
pause

stage "Install the scorer"
say "The blind scorer is a placeholder until M0 builds it. You run it as $KEY_USER with your"
say "password (sudo -u $KEY_USER $SCORER); there is no password-free rule (ADR 0026, amended)."
if [ -e "$SCORER" ] && ! grep -q "scorer not built yet" "$SCORER" 2>/dev/null; then
  note "$SCORER is the real scorer (scripts/owner/keys-custody.sh installs it); left as it is."
else
  tmp=$(mktemp)
  printf '#!/usr/bin/env bash\necho "vx-score: scorer not built yet (ADR 0026)"\n' > "$tmp"
  sudo install -o root -g root -m 755 "$tmp" "$SCORER"
  rm -f "$tmp"
fi
if sudo test -f "$SCORER_RULE"; then
  warn "An old password-free rule exists at $SCORER_RULE: run scripts/owner/scorer-rule-remove.sh."
fi
printf '  %s✓ installed%s %s\n' "$GREEN" "$RESET" "$SCORER"
pause

stage "Move your Answer Keys in"
say "Answer Keys: the Sample Project generator's inputs (only you know where they are),"
say "Hand Takeoffs when they exist, Held-out Sets as they arrive."
say "For each, give its full path. [m]ove takes it away from your user entirely;"
say "[c]opy leaves the original (use copy only for things inside ~/vextrus-cad,"
say "which the guard already fences, so the laboratory keeps working)."
while true; do
  KEY_PATH=""
  ask KEY_PATH "Path of an Answer Key (Enter when done):"
  [[ -z "${KEY_PATH:-}" ]] && break
  if [[ ! -e "$KEY_PATH" ]]; then warn "Not found: $KEY_PATH"; continue; fi
  ask KEY_MODE "[m]ove or [c]opy?"
  name=$(basename "$KEY_PATH")
  if [[ "$KEY_MODE" =~ ^[Mm] ]] && confirm "Move $KEY_PATH into $KEY_DIR/$name?"; then
    sudo mv "$KEY_PATH" "$KEY_DIR/$name"
  elif [[ "$KEY_MODE" =~ ^[Cc] ]] && confirm "Copy $KEY_PATH into $KEY_DIR/$name?"; then
    sudo cp -a "$KEY_PATH" "$KEY_DIR/$name"
  else
    note "skipped"; continue
  fi
  sudo chown -R "$KEY_USER:$KEY_USER" "$KEY_DIR/$name"
  sudo chmod -R go-rwx "$KEY_DIR/$name"
  printf '  %s✓%s %s is now %s-only\n' "$GREEN" "$RESET" "$name" "$KEY_USER"
done

stage "Put a password back on sudo"
say "This removes the password-free rule for $ME. Afterwards sudo asks your password."
say "If anything goes wrong, from Windows run:  wsl -u root   (it always works)."
if sudo grep -qs "NOPASSWD" /etc/sudoers; then
  warn "/etc/sudoers itself also has a NOPASSWD line. This wizard does not edit it;"
  warn "tell Claude, or remove it yourself with: sudo visudo"
fi
if sudo test -f "$OLD_RULE"; then
  note "Current $OLD_RULE:"; sudo cat "$OLD_RULE" | sed 's/^/    /'
  if confirm "Remove $OLD_RULE (a backup goes to /root/90-riz.bak)?"; then
    sudo cp -a "$OLD_RULE" /root/90-riz.bak
    sudo rm "$OLD_RULE"
    if sudo visudo -c >/dev/null; then
      printf '  %s✓ removed; sudoers still valid%s\n' "$GREEN" "$RESET"
    else
      sudo cp -a /root/90-riz.bak "$OLD_RULE"
      warn "sudoers failed to validate, so the rule was restored. Tell Claude."
      exit 1
    fi
  else
    SKIPPED+=("sudo still needs no password: remove $OLD_RULE")
  fi
else
  note "$OLD_RULE is already gone."
fi
pause

stage "Prove the fence"
sudo -k
pass=0; fail=0
check() {
  if eval "$2" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; pass=$((pass+1))
  else
    printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; fail=$((fail+1)); SKIPPED+=("fence check failed: $1")
  fi
}
check "your user cannot list $KEY_DIR"      "! ls '$KEY_DIR'"
check "sudo without a password is refused"  "! sudo -n true"
check "the scorer does not run without a password" "! sudo -n -u '$KEY_USER' '$SCORER'"
say ""
say "$pass passed, $fail failed."
note "Known residual hole: Windows interop can run 'wsl.exe -u root' from inside Linux."
note "The guard refuses that in agent sessions; tell Claude if you also want interop off."
pause

finish
