# Generated by Django 6.1.1 on 2026-10-07, then row-level security, the same-tenant keys and vextrus_app's
# rights written by hand (ticket S16-M; docs/data-model.md §2 and §3.4). Run as the owner.
#
# - Every measurement table is a Library table (L): row-level security ENABLED, never forced, an
#   own-tenant policy, and a FOR SELECT policy admitting the acting tenant's Market Library through
#   app.library_id. vextrus_app may only SELECT them (sync_library writes them as the owner).
# - A reference between them names a row of the same tenant: a composite key on (tenant_id, x_id)
#   beside Django's own, deferred.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import vextrus.platform.ids

APP = settings.VEXTRUS_APP_ROLE

OWN_TENANT = "tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid"
LIBRARY = "tenant_id = nullif(current_setting('app.library_id', true), '')::uuid"

TABLES = (
    "measurement_ruleset",
    "measurement_rulesetversion",
    "measurement_measurementrule",
    "measurement_boqitem",
    "measurement_boqitembillingunit",
    "measurement_rebarratio",
)

POLICIES = [
    *(f"alter table {table} enable row level security" for table in TABLES),
    *(f"create policy own_tenant on {table} using ({OWN_TENANT})" for table in TABLES),
    *(f"create policy library_reads on {table} for select using ({LIBRARY})" for table in TABLES),
]
POLICIES_REVERSE = [
    *(f"drop policy library_reads on {table}" for table in TABLES),
    *(f"drop policy own_tenant on {table}" for table in TABLES),
    *(f"alter table {table} disable row level security" for table in TABLES),
]

# (table, column, the table it names): each reference held inside its row's tenant.
REFERENCES = (
    ("measurement_rulesetversion", "rule_set_id", "measurement_ruleset"),
    ("measurement_measurementrule", "version_id", "measurement_rulesetversion"),
    ("measurement_boqitem", "version_id", "measurement_rulesetversion"),
    ("measurement_boqitembillingunit", "item_id", "measurement_boqitem"),
    ("measurement_rebarratio", "version_id", "measurement_rulesetversion"),
)


def _key_name(table, column):
    return f"{table}_{column}_same_tenant"[:63]


KEYS = [
    f"""alter table {table} add constraint {_key_name(table, column)}
          foreign key (tenant_id, {column}) references {target} (tenant_id, id)
          deferrable initially deferred"""
    for table, column, target in REFERENCES
]
KEYS_REVERSE = [
    f"alter table {table} drop constraint {_key_name(table, column)}"
    for table, column, _target in reversed(REFERENCES)
]

RIGHTS = [f"revoke insert, update, delete on {table} from {APP}" for table in TABLES]
RIGHTS_REVERSE = [f"grant insert, update, delete on {table} to {APP}" for table in TABLES]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Its default privileges give vextrus_app its rights on these tables.
        ("platform", "0008_jev"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        editable=False, help_text="The Market's Library tenant."
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "name"), name="measurement_ruleset_name"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant_id", "id"), name="measurement_ruleset_tenant_id"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RuleSetVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("number", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=16)),
                ("content_hash", models.CharField(max_length=80)),
                (
                    "rule_set",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="measurement.ruleset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RebarRatio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("family_key", models.CharField(max_length=64)),
                ("band", models.UUIDField(blank=True, null=True)),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                ("unit", models.CharField(max_length=16)),
                ("confidence", models.CharField(blank=True, default="", max_length=16)),
                ("source", models.CharField(blank=True, default="", max_length=300)),
                (
                    "version",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="measurement.rulesetversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeasurementRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("code", models.CharField(max_length=16)),
                ("kind", models.CharField(max_length=24)),
                ("family_key", models.CharField(blank=True, default="", max_length=64)),
                (
                    "words",
                    models.JSONField(
                        help_text="Its words per language: {language: text}; never a standard's text."
                    ),
                ),
                (
                    "cites",
                    models.CharField(
                        help_text="The clause it follows, by number only.",
                        max_length=200,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                ("source", models.CharField(blank=True, default="", max_length=200)),
                (
                    "version",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="measurement.rulesetversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoqItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("item_code", models.CharField(max_length=64)),
                (
                    "labels",
                    models.JSONField(
                        help_text="Its description per language: {language: text}."
                    ),
                ),
                ("trade", models.CharField(max_length=40)),
                ("boq_section", models.CharField(max_length=40)),
                (
                    "group",
                    models.CharField(help_text="Its element class.", max_length=40),
                ),
                ("stage_kind", models.CharField(blank=True, default="", max_length=40)),
                ("basis_kind", models.CharField(max_length=16)),
                ("supply_kind", models.CharField(max_length=24)),
                ("labour_measure", models.BooleanField(default=False)),
                ("description_template", models.JSONField(default=dict)),
                (
                    "version",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="measurement.rulesetversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoqItemBillingUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("unit_system", models.CharField(max_length=16)),
                ("billing_unit", models.CharField(max_length=16)),
                (
                    "unit_si",
                    models.CharField(
                        help_text="The SI unit a Measurement Line holds.", max_length=16
                    ),
                ),
                ("si_per_unit", models.DecimalField(decimal_places=12, max_digits=24)),
                ("line_decimals", models.PositiveSmallIntegerField(default=2)),
                ("total_decimals", models.PositiveSmallIntegerField(default=2)),
                (
                    "item",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="measurement.boqitem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "item", "unit_system"),
                        name="measurement_billingunit_system",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("si_per_unit__gt", 0)),
                        name="measurement_billingunit_factor",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rulesetversion",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "rule_set", "number"),
                name="measurement_rsv_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulesetversion",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "id"), name="measurement_rsv_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="rulesetversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("draft", "published"))),
                name="measurement_rsv_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="rebarratio",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "version", "family_key", "band"),
                name="measurement_rebarratio_band",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="rebarratio",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit__in", ("kg/cft", "kg/m3"))),
                name="measurement_rebarratio_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="rebarratio",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gt", 0)),
                name="measurement_rebarratio_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementrule",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "version", "code"), name="measurement_rule_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        (
                            "quantity",
                            "junction",
                            "rebar_detailing",
                            "stage",
                            "rounding",
                            "run_by_rule",
                        ),
                    )
                ),
                name="measurement_rule_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="boqitem",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "version", "item_code"),
                name="measurement_boqitem_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="boqitem",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "id"), name="measurement_boqitem_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="boqitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("basis_kind__in", ("measured", "lump_sum", "provisional"))
                ),
                name="measurement_boqitem_basis",
            ),
        ),
        migrations.AddConstraint(
            model_name="boqitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("supply_kind__in", ("developer_materials", "material_and_labour"))
                ),
                name="measurement_boqitem_supply",
            ),
        ),
        migrations.RunSQL(POLICIES, POLICIES_REVERSE),
        migrations.RunSQL(KEYS, KEYS_REVERSE),
        migrations.RunSQL(RIGHTS, RIGHTS_REVERSE),
    ]
