/*
 * The shared pieces (docs/design/m0-screens.md §3; ticket 01b). Later tickets import from here and
 * never restyle them; a change to a piece is a change to this folder, gated on /dev/specimen.
 */
export * from './glyphs'
export { AccessChip, type AccessChipProps } from './AccessChip'
export { Button, IconButton, buttonVariants, type ButtonProps } from './Button'
export { cn } from './cn'
export { Count } from './Count'
export { DesktopOnly, NarrowNotice, PhoneNotice, DESKTOP_FROM_PX, PHONE_BELOW_PX } from './DesktopOnly'
export { DrawingText, type DrawingTextKind } from './DrawingText'
export { Empty } from './Empty'
export { ErrorBar } from './ErrorBar'
export { FieldError } from './FieldError'
export { Checkbox, type CheckboxProps } from './Checkbox'
export { Kbd, KeyCombo } from './Kbd'
export { List, type ListProps } from './List'
export { LtrCanvas } from './LtrCanvas'
export { NOTATION_KINDS, isolateLtr, isolateOwn, notationProblems, type NotationKind } from './notation'
export { ProgressLine } from './ProgressLine'
export { ReadOnlyChip } from './ReadOnlyChip'
export { Segmented, type SegmentedOption } from './Segmented'
export { Skeleton, SkeletonBar } from './Skeleton'
export { StatusMark, type Status } from './StatusMark'
export { TextField, type TextFieldProps } from './TextField'
export { ToastProvider, ToastViewport, useToast, TOAST_MS, type ToastMessage } from './Toast'
export { UiProviders } from './UiProviders'
export { KeyMapProvider, KeyRegion, KeyScope, useActiveKeys, useKeyMap, useKeys } from './keys/KeyMapProvider'
export { KeysOverlay } from './keys/KeysOverlay'
export { KeyMap, KeyMapError, normaliseCombo, type Binding, type KeyGroup, type Scope, type ScopeLevel } from './keys/registry'
export { expectKeyMapSound, keyMapProblems } from './keys/testing'
