# Generated by Django 6.1.1 on 2026-09-28 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import vextrus.platform.ids


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("name", models.CharField(max_length=200)),
                ("library_id", models.UUIDField(editable=False)),
                ("home_region", models.CharField(max_length=32)),
                ("is_library", models.BooleanField(default=False, editable=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("kind", models.CharField(max_length=120)),
                ("project_id", models.UUIDField(blank=True, null=True)),
                ("building_id", models.UUIDField(blank=True, null=True)),
                ("subject_type", models.CharField(max_length=60)),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                ("actor_user_id", models.UUIDField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "occurred_at"],
                        name="platform_event_tenant_time",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                (
                    "labels",
                    models.JSONField(
                        help_text="Its name per language: {language: name}."
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(help_text="ISO 4217.", max_length=3),
                ),
                ("currency_minor_units", models.PositiveSmallIntegerField()),
                ("currency_symbol", models.CharField(max_length=8)),
                (
                    "currency_symbol_position",
                    models.JSONField(
                        help_text='Per language, "before" or "after" the amount.'
                    ),
                ),
                (
                    "grouping",
                    models.CharField(help_text='"lakh" or "thousands".', max_length=16),
                ),
                (
                    "digits",
                    models.CharField(
                        help_text='The numbering system, as "latn".', max_length=8
                    ),
                ),
                (
                    "borrowed_locales",
                    models.JSONField(
                        help_text="The locale each language borrows for its formats: {language: locale}."
                    ),
                ),
                (
                    "unit_systems",
                    models.JSONField(help_text="The unit systems offered, in order."),
                ),
                ("default_unit_system", models.CharField(max_length=16)),
                (
                    "languages",
                    models.JSONField(help_text="The languages offered, in order."),
                ),
                ("default_language", models.CharField(max_length=8)),
                (
                    "time_zone",
                    models.CharField(help_text="An IANA time zone.", max_length=64),
                ),
                (
                    "days_off",
                    models.JSONField(
                        help_text="The work week's days off, as ISO weekdays (1 is Monday)."
                    ),
                ),
                ("default_home_region", models.CharField(max_length=32)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="platform.developer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="developer",
            name="market",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="platform.market",
            ),
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("qs", "QS"),
                            ("md", "MD"),
                            ("vextrus_engineer", "Vextrus Engineer"),
                            ("guest", "Guest"),
                        ],
                        max_length=24,
                    ),
                ),
                ("outside_org", models.CharField(blank=True, max_length=200)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("starts_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("invited_email", models.EmailField(blank=True, max_length=254)),
                (
                    "invite_token_hash",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                (
                    "invite_expires_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="platform.developer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembershipProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("project_id", models.UUIDField()),
                (
                    "membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="platform.membership",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("code",), name="platform_market_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="platform_market_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency_minor_units__lte", 4)),
                name="platform_market_minor_units_fit",
            ),
        ),
        migrations.AddIndex(
            model_name="developer",
            index=models.Index(fields=["tenant_id"], name="platform_developer_tenant"),
        ),
        migrations.AddConstraint(
            model_name="developer",
            constraint=models.CheckConstraint(
                condition=models.Q(("tenant_id", models.F("id"))),
                name="platform_developer_is_its_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="developer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_library", False),
                    ("library_id", models.F("id")),
                    _connector="OR",
                ),
                name="platform_developer_library_is_itself",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["user"], name="platform_membership_user"),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="platform_membership_tenant_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True), ("user__isnull", False)
                ),
                fields=("tenant", "user"),
                name="platform_membership_one_live_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("invite_token_hash", ""), _negated=True),
                fields=("tenant", "invite_token_hash"),
                name="platform_membership_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("role__in", ["qs", "md", "vextrus_engineer", "guest"])
                ),
                name="platform_membership_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "vextrus_engineer"), _negated=True),
                    ("expires_at__isnull", False),
                    _connector="OR",
                ),
                name="platform_membership_engineer_ends",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("accepted_at__isnull", True), ("user__isnull", True)),
                    models.Q(("accepted_at__isnull", False), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="platform_membership_accepted_with_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    models.Q(
                        ("invite_expires_at__isnull", False),
                        models.Q(("invite_token_hash", ""), _negated=True),
                        models.Q(("invited_email", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="platform_membership_invitation_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipproject",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "membership", "project_id"),
                name="platform_membershipproject_unique",
            ),
        ),
    ]
