# Generated by Django 6.1.1 on 2026-09-28 10:53; the SQL below is written by hand (ticket 09), run as
# the owner.
#
# - StoredFile is a tenant table: row-level security enabled (never forced) with its own-tenant
#   policy; its key must begin with its tenant's id, then its Project's; vextrus_app may add a row but
#   never change or delete one (a key names one content for good).
# - Procrastinate's tables stay global (the policy-coverage test's allowlist gives each reason): a
#   worker takes any tenant's job, so no tenant setting can filter them. What keeps a tenant's jobs
#   its own is the job wall below and the step runner (platform.services.jobs).
# - The job wall: acting as vextrus_app, a job whose arguments name a tenant may be inserted only
#   while acting in that tenant (app.tenant_id), and no job's arguments may ever be rewritten, so the
#   app cannot make the worker act in another Developer. The function runs as its caller (not
#   SECURITY DEFINER), so current_user is the app's role; the owner passes.
# - procrastinate_events is a job's history: vextrus_app may add to it (Procrastinate's triggers do)
#   but never change or delete it; deleting a job cascades to its events as the table's owner.
# - vextrus_app keeps SELECT, INSERT, UPDATE and DELETE on Procrastinate's other tables, which the
#   worker needs (it registers, beats and prunes workers, fetches and finishes jobs, defers periodic
#   jobs); never TRUNCATE (migration 0003).

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import vextrus.platform.ids

APP = settings.VEXTRUS_APP_ROLE
OWN_TENANT = "tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid"

STORED_FILE = [
    "alter table platform_storedfile enable row level security",
    f"create policy own_tenant on platform_storedfile using ({OWN_TENANT})",
    """alter table platform_storedfile add constraint platform_storedfile_key_prefix
         check (starts_with(key, tenant_id::text || '/' || project_id::text || '/'))""",
    f"revoke update, delete on platform_storedfile from {APP}",
]
STORED_FILE_REVERSE = [
    f"grant update, delete on platform_storedfile to {APP}",
    "alter table platform_storedfile drop constraint platform_storedfile_key_prefix",
    "drop policy own_tenant on platform_storedfile",
    "alter table platform_storedfile disable row level security",
]

JOB_WALL = [
    f"""
    create function public.platform_job_tenant_wall() returns trigger
    language plpgsql
    set search_path = pg_catalog, pg_temp
    as $$
    begin
      if current_user = '{APP}' then
        if tg_op = 'UPDATE' and new.args is distinct from old.args then
          raise exception '{APP} may not rewrite a job''s arguments' using errcode = '42501';
        end if;
        if tg_op = 'INSERT' and new.args ? 'tenant_id'
           and (new.args ->> 'tenant_id')
               is distinct from nullif(current_setting('app.tenant_id', true), '') then
          raise exception '{APP} may defer a job only for the tenant it acts in'
            using errcode = '42501';
        end if;
      end if;
      return new;
    end
    $$
    """,
    "revoke all on function public.platform_job_tenant_wall() from public",
    """
    create trigger platform_job_tenant_wall
      before insert or update on public.procrastinate_jobs
      for each row execute function public.platform_job_tenant_wall()
    """,
    f"revoke update, delete on procrastinate_events from {APP}",
]
JOB_WALL_REVERSE = [
    f"grant update, delete on procrastinate_events to {APP}",
    "drop trigger platform_job_tenant_wall on public.procrastinate_jobs",
    "drop function public.platform_job_tenant_wall()",
]


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0005_user_staff_wall"),
        # The job wall is a trigger on Procrastinate's table.
        ("procrastinate", "0041_post_retry_failed_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("project_id", models.UUIDField()),
                ("key", models.CharField(max_length=1200)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("derived", "Derived"),
                            ("export", "Export"),
                            ("evidence", "Evidence"),
                        ],
                        max_length=16,
                    ),
                ),
                ("media_type", models.CharField(max_length=127)),
                ("size", models.PositiveBigIntegerField()),
                (
                    "producer",
                    models.CharField(help_text="What made it: `upload`, a reader, …", max_length=64),
                ),
                ("producer_version", models.CharField(blank=True, max_length=64)),
                (
                    "source_sha256",
                    models.CharField(
                        blank=True,
                        help_text="The file it was derived from, if any.",
                        max_length=64,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "sha256"],
                        name="platform_storedfile_sha256",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant_id", "key"), name="platform_storedfile_key"),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["original", "derived", "export", "evidence"])),
                        name="platform_storedfile_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "key__regex",
                                "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(/[A-Za-z0-9_][A-Za-z0-9._@+-]{0,127}){1,8}$",
                            )
                        ),
                        name="platform_storedfile_key_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sha256__regex", "^[0-9a-f]{64}$"),
                            models.Q(
                                ("source_sha256", ""),
                                ("source_sha256__regex", "^[0-9a-f]{64}$"),
                                _connector="OR",
                            ),
                        ),
                        name="platform_storedfile_sha256_hex",
                    ),
                ],
            },
        ),
        migrations.RunSQL(STORED_FILE, STORED_FILE_REVERSE),
        migrations.RunSQL(JOB_WALL, JOB_WALL_REVERSE),
    ]
