# Generated by Django 6.1.1 on 2026-09-28 10:53; the SQL below is written by hand (ticket 09), run as
# the owner.
#
# - StoredFile is a tenant table: row-level security enabled (never forced) with its own-tenant
#   policy; its key must begin with its tenant's id, then its Project's; vextrus_app may add a row but
#   never change or delete one (a key names one content for good).
# - Procrastinate's tables stay global (the policy-coverage test's allowlist gives each reason): a
#   worker takes any tenant's job, so no tenant setting can filter them. What keeps a tenant's jobs
#   its own is the job wall below and the step runner (platform.services.jobs).
# - The job wall (a trigger on procrastinate_jobs), so the app cannot make the worker act in another
#   Developer or as another person, nor disturb another Developer's jobs. Acting as vextrus_app:
#   - a job is inserted waiting, naming the tenant the app acts in (or, acting in none, no tenant:
#     Procrastinate's periodic jobs), the user it acts as (or none), and, while acting in a tenant, a
#     lock and queueing lock that begin with that tenant's id;
#   - a job's arguments, task, queue and locks never change; an ended job never reopens; its tries
#     never go back; and while acting in a tenant, only that tenant's jobs change (the worker, acting
#     in none, fetches, finishes and retries any);
#   - a running job is neither ended nor sent back to wait while a try still holds it (the step
#     runner holds a session advisory lock on the job's id for the try's life, which PostgreSQL
#     lets go when the worker dies), so a retry never runs one job in two tries at once and a
#     superseded try never ends the job its successor runs.
#   The function runs as its caller (not SECURITY DEFINER), so current_user is the app's role; the
#   owner passes. Like row-level security, it holds the app's code to its tenant: a role that can run
#   any SQL can also set app.tenant_id.
# - vextrus_app may not delete a job (the worker keeps every job: Procrastinate's `delete_jobs` is
#   "never"); old jobs are the owner's to clear.
# - procrastinate_events is a job's history: vextrus_app may add to it (Procrastinate's triggers do)
#   but never change or delete it.
# - vextrus_app keeps SELECT, INSERT, UPDATE and DELETE on procrastinate_workers and
#   procrastinate_periodic_defers, and SELECT, INSERT and UPDATE on procrastinate_jobs, which the
#   worker needs (it registers, beats and prunes workers, fetches, retries and finishes jobs, defers
#   periodic jobs); never TRUNCATE (migration 0003).

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import vextrus.platform.ids

APP = settings.VEXTRUS_APP_ROLE
OWN_TENANT = "tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid"

STORED_FILE = [
    "alter table platform_storedfile enable row level security",
    f"create policy own_tenant on platform_storedfile using ({OWN_TENANT})",
    """alter table platform_storedfile add constraint platform_storedfile_key_prefix
         check (starts_with(key, tenant_id::text || '/' || project_id::text || '/'))""",
    f"revoke update, delete on platform_storedfile from {APP}",
]
STORED_FILE_REVERSE = [
    f"grant update, delete on platform_storedfile to {APP}",
    "alter table platform_storedfile drop constraint platform_storedfile_key_prefix",
    "drop policy own_tenant on platform_storedfile",
    "alter table platform_storedfile disable row level security",
]

JOB_WALL = [
    f"""
    create function public.platform_job_tenant_wall() returns trigger
    language plpgsql
    set search_path = pg_catalog, pg_temp
    as $$
    declare
      acting_tenant text := nullif(current_setting('app.tenant_id', true), '');
      acting_user text := nullif(current_setting('app.user_id', true), '');
    begin
      if current_user <> '{APP}' then
        return new;
      end if;
      if tg_op = 'INSERT' then
        if (new.args ->> 'tenant_id') is distinct from acting_tenant
           and (new.args ? 'tenant_id' or acting_tenant is not null) then
          raise exception '{APP} may defer a job only for the tenant it acts in'
            using errcode = '42501';
        end if;
        if new.args ? 'user_id' and (new.args ->> 'user_id') is distinct from acting_user then
          raise exception '{APP} may defer a job only for the user it acts as'
            using errcode = '42501';
        end if;
        if acting_tenant is not null
           and not (coalesce(starts_with(new.lock, acting_tenant || ':'), true)
                    and coalesce(starts_with(new.queueing_lock, acting_tenant || ':'), true)) then
          raise exception '{APP} may lock a job only under the tenant it acts in'
            using errcode = '42501';
        end if;
        if new.status <> 'todo' or new.attempts <> 0 or new.abort_requested
           or new.worker_id is not null then
          raise exception '{APP} defers a job only as waiting' using errcode = '42501';
        end if;
      else
        if new.args is distinct from old.args or new.task_name is distinct from old.task_name
           or new.queue_name is distinct from old.queue_name or new.lock is distinct from old.lock
           or new.queueing_lock is distinct from old.queueing_lock then
          raise exception '{APP} may not change a job''s task, queue, lock or arguments'
            using errcode = '42501';
        end if;
        if old.status in ('succeeded', 'failed', 'cancelled', 'aborted')
           and new.status is distinct from old.status then
          raise exception '{APP} may not reopen a job that has ended' using errcode = '42501';
        end if;
        if new.attempts < old.attempts then
          raise exception '{APP} may not take back a job''s tries' using errcode = '42501';
        end if;
        -- A running try holds its job (a session advisory lock on the job's id, taken by the
        -- step runner); while it does, nobody else ends the job or sends it back to wait.
        if old.status = 'doing' and new.status is distinct from 'doing'
           and not pg_try_advisory_xact_lock((old.id >> 31)::int, (old.id & 2147483647)::int) then
          raise exception '{APP} may not end or retry a job while a try is still running it'
            using errcode = '55P03';
        end if;
        if acting_tenant is not null and (old.args ->> 'tenant_id') is distinct from acting_tenant then
          raise exception '{APP} may change only the jobs of the tenant it acts in'
            using errcode = '42501';
        end if;
      end if;
      return new;
    end
    $$
    """,
    "revoke all on function public.platform_job_tenant_wall() from public",
    """
    create trigger platform_job_tenant_wall
      before insert or update on public.procrastinate_jobs
      for each row execute function public.platform_job_tenant_wall()
    """,
    f"revoke delete on procrastinate_jobs from {APP}",
    f"revoke update, delete on procrastinate_events from {APP}",
]
JOB_WALL_REVERSE = [
    f"grant update, delete on procrastinate_events to {APP}",
    f"grant delete on procrastinate_jobs to {APP}",
    "drop trigger platform_job_tenant_wall on public.procrastinate_jobs",
    "drop function public.platform_job_tenant_wall()",
]


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0005_user_staff_wall"),
        # The job wall is a trigger on Procrastinate's table.
        ("procrastinate", "0041_post_retry_failed_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField()),
                ("project_id", models.UUIDField()),
                ("key", models.CharField(max_length=1200)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("derived", "Derived"),
                            ("export", "Export"),
                            ("evidence", "Evidence"),
                        ],
                        max_length=16,
                    ),
                ),
                ("media_type", models.CharField(max_length=127)),
                ("size", models.PositiveBigIntegerField()),
                (
                    "producer",
                    models.CharField(help_text="What made it: `upload`, a reader, …", max_length=64),
                ),
                ("producer_version", models.CharField(blank=True, max_length=64)),
                (
                    "source_sha256",
                    models.CharField(
                        blank=True,
                        help_text="The file it was derived from, if any.",
                        max_length=64,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "sha256"],
                        name="platform_storedfile_sha256",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant_id", "key"), name="platform_storedfile_key"),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["original", "derived", "export", "evidence"])),
                        name="platform_storedfile_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "key__regex",
                                "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(/[A-Za-z0-9_][A-Za-z0-9._@+-]{0,127}){1,8}$",
                            )
                        ),
                        name="platform_storedfile_key_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sha256__regex", "^[0-9a-f]{64}$"),
                            models.Q(
                                ("source_sha256", ""),
                                ("source_sha256__regex", "^[0-9a-f]{64}$"),
                                _connector="OR",
                            ),
                        ),
                        name="platform_storedfile_sha256_hex",
                    ),
                ],
            },
        ),
        migrations.RunSQL(STORED_FILE, STORED_FILE_REVERSE),
        migrations.RunSQL(JOB_WALL, JOB_WALL_REVERSE),
    ]
