# Generated by Django 6.1.1 on 2026-09-28 20:30; the SQL below is written by hand (ticket 15), run as
# the owner.
#
# - JevAnswer (the per-tenant answer cache) and JevOverride (the override log) are tenant tables:
#   row-level security enabled (never forced) with the own-tenant policy for reads and writes alike.
# - Both are append-only for vextrus_app, which default privileges would otherwise let update and
#   delete (0003): an answer never changes, since its key includes the model, and an override is a
#   log. So vextrus_app may add rows but never change or delete one, nor upsert (which needs UPDATE).
# - An answer's choice is one of its options, its options a list of two to 255 keys, its
#   probabilities an object holding its choice; its confidence lies in 0-1 (a check in the model).
# - An override's (tenant, answer, node, model, Jev's choice) must be its answer's, by a composite
#   key, as 0003 holds a MembershipProject to its Membership's tenant: the override carries its
#   answer's node, model and choice and no other, and never another tenant's answer. The QS's choice
#   is never Jev's (a check in the model) and is one its answer offered (a trigger: a check cannot
#   read another row). The trigger runs as its caller, under the caller's row-level security, after
#   the row's own checks, its policy and its keys, so each refusal names its own rule.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import vextrus.platform.ids

APP = settings.VEXTRUS_APP_ROLE
OWN_TENANT = "tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid"
TABLES = ("platform_jevanswer", "platform_jevoverride")

TENANCY = [
    *(f"alter table {table} enable row level security" for table in TABLES),
    *(f"create policy own_tenant on {table} using ({OWN_TENANT})" for table in TABLES),
    *(f"revoke update, delete on {table} from {APP}" for table in TABLES),
]
TENANCY_REVERSE = [
    *(f"grant update, delete on {table} to {APP}" for table in TABLES),
    *(f"drop policy own_tenant on {table}" for table in TABLES),
    *(f"alter table {table} disable row level security" for table in TABLES),
]

ANSWER = [
    """alter table platform_jevanswer add constraint platform_jevanswer_offered
         check (jsonb_typeof(options) = 'array'
                and jsonb_array_length(options) between 2 and 255
                and options ? choice
                and jsonb_typeof(probabilities) = 'object'
                and probabilities ? choice)""",
]
ANSWER_REVERSE = [
    "alter table platform_jevanswer drop constraint platform_jevanswer_offered",
]

OVERRIDE = [
    """alter table platform_jevoverride add constraint platform_jevoverride_its_answer
         foreign key (tenant_id, answer_id, node, model_version, jev_choice)
         references platform_jevanswer (tenant_id, id, node, model_version, choice)""",
    """
    create function public.platform_jevoverride_offered() returns trigger
    language plpgsql
    set search_path = pg_catalog, pg_temp
    as $$
    begin
      if not exists (select 1 from public.platform_jevanswer a
                      where a.tenant_id = new.tenant_id and a.id = new.answer_id
                        and a.options ? new.qs_choice) then
        raise exception 'an override''s choice must be one its answer offered'
          using errcode = '23514';
      end if;
      return null;
    end
    $$
    """,
    "revoke all on function public.platform_jevoverride_offered() from public",
    """
    create trigger platform_jevoverride_offered
      after insert on public.platform_jevoverride
      for each row execute function public.platform_jevoverride_offered()
    """,
]
OVERRIDE_REVERSE = [
    "drop trigger platform_jevoverride_offered on public.platform_jevoverride",
    "drop function public.platform_jevoverride_offered()",
    "alter table platform_jevoverride drop constraint platform_jevoverride_its_answer",
]


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0006_stored_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='JevAnswer',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('cache_key', models.CharField(max_length=64)),
                ('node', models.CharField(max_length=64)),
                ('model_version', models.CharField(max_length=64)),
                ('options', models.JSONField(help_text='The option keys offered, in order.')),
                ('choice', models.CharField(max_length=64)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('probabilities', models.JSONField(help_text='{option: probability as a decimal string}.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'node', 'model_version'], name='platform_jevanswer_node')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'cache_key'), name='platform_jevanswer_key'), models.UniqueConstraint(fields=('tenant_id', 'id', 'node', 'model_version', 'choice'), name='platform_jevanswer_what'), models.CheckConstraint(condition=models.Q(('cache_key__regex', '^[0-9a-f]{64}$')), name='platform_jevanswer_key_shape'), models.CheckConstraint(condition=models.Q(('node__regex', '^[a-z][a-z0-9_]{0,63}$'), ('choice__regex', '^[a-z][a-z0-9_]{0,63}$')), name='platform_jevanswer_keys'), models.CheckConstraint(condition=models.Q(('model_version__regex', '^[a-z0-9][a-z0-9._-]{0,63}$')), name='platform_jevanswer_model_shape'), models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='platform_jevanswer_confidence')],
            },
        ),
        migrations.CreateModel(
            name='JevOverride',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('node', models.CharField(max_length=64)),
                ('model_version', models.CharField(max_length=64)),
                ('subject_id', models.UUIDField()),
                ('jev_choice', models.CharField(max_length=64)),
                ('qs_choice', models.CharField(max_length=64)),
                ('at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.jevanswer')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'answer'], name='platform_jevoverride_answer'), models.Index(fields=['tenant_id', 'node', 'model_version'], name='platform_jevoverride_node')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qs_choice__regex', '^[a-z][a-z0-9_]{0,63}$'), models.Q(('qs_choice', models.F('jev_choice')), _negated=True)), name='platform_jevoverride_qs_not_jev')],
            },
        ),
        migrations.RunSQL(TENANCY, TENANCY_REVERSE),
        migrations.RunSQL(ANSWER, ANSWER_REVERSE),
        migrations.RunSQL(OVERRIDE, OVERRIDE_REVERSE),
    ]
