# Generated by Django 6.1.1 on 2026-09-29 15:16; the data step written by hand (ticket 22, the design
# gate's M1). A Market's date order: how its drawings write a date in figures ("12.09.2026" is 12 Sep
# 2026 in a day-month-year Market), so a title block's date is read, and sent as ISO, by the Market's
# data and never by code. Bangladesh's drawings write day, month, year. Run as the owner, which
# writes Library rows; `seed` puts it back after the tests' flush (vextrus/testing/tenancy.py).

from django.db import migrations, models

DATE_ORDER = {"BD": "DMY"}
"""Each Market's date order, by its code."""


def seed(Market, using):
    """Write (or put back) each Market's date order, as above."""
    for code, order in DATE_ORDER.items():
        Market.objects.using(using).filter(code=code).update(date_order=order)


def forward(apps, schema_editor):
    seed(apps.get_model("platform", "Market"), schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0008_jev"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="date_order",
            field=models.CharField(
                blank=True,
                db_default="",
                help_text='How its drawings write a date in figures: "DMY", "MDY" or "YMD"; "" when unknown.',
                max_length=3,
            ),
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_order__in", ["", "DMY", "MDY", "YMD"])),
                name="platform_market_date_order_known",
            ),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
