#!/usr/bin/env node
/*
 * The generated API types (ADR 0022; docs/plans/M0.md, "The shape of M0's code"): src/api/schema.gen.ts,
 * built from the OpenAPI schema and never committed. `npm run api:types`; web.yml runs it before the
 * typecheck and the tests.
 *
 *   OPENAPI_SCHEMA=<file|URL> npm run api:types   the schema given (a running server's, say)
 *   npm run api:types                             the schema exported from this checkout's backend
 *                                                 (`uv run --no-sync manage.py export_openapi_schema`;
 *                                                 no database needed)
 *
 * `--enum-values` also emits each enum as an array, so the web's test can read every message code the
 * machine may send (`messageCodeValues`, src/format/message-codes.node.test.ts).
 */
import { spawnSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const web = fileURLToPath(new URL('..', import.meta.url))
const root = fileURLToPath(new URL('../..', import.meta.url))
const OUT = 'src/api/schema.gen.ts'

function run(command, args, cwd) {
  const r = spawnSync(command, args, { cwd, stdio: 'inherit' })
  if (r.status !== 0) {
    console.error(`\napi-types: \`${[command, ...args].join(' ')}\` failed`)
    process.exit(r.status ?? 1)
  }
}

let schema = process.env.OPENAPI_SCHEMA
let scratch
if (!schema) {
  scratch = mkdtempSync(join(tmpdir(), 'vextrus-openapi-'))
  schema = join(scratch, 'openapi.json')
  run('uv', ['run', '--no-sync', 'manage.py', 'export_openapi_schema', '--api', 'vextrus.api.api', '--output', schema], root)
}
try {
  run('node_modules/.bin/openapi-typescript', [schema, '--enum-values', '-o', OUT], web)
  // Generated code is not ours to lint: openapi-typescript 7.13's helpers trip `noUnusedLocals`, and it
  // types an empty enum's array as `never`, which `[]` does not satisfy (no module has a message code
  // yet). Its exported types still check wherever the app uses them.
  const path = join(web, OUT)
  writeFileSync(path, `// @ts-nocheck -- generated by scripts/api-types.mjs; never edited or committed\n${readFileSync(path, 'utf8')}`)
} finally {
  if (scratch) {
    rmSync(join(scratch, 'openapi.json'), { force: true })
    rmdirSync(scratch)
  }
}
