// R-SPINE-060: S-Home's own table — the projects home at /t/{tenant}, its cards, its form and the
// two empty regions that say why they are empty. The copy is the screen's Design Decision § 3,
// verbatim; a screen spells no string of its own.
export const home = {
  home_create_project: "New project",
  home_form_create_heading: "New project",
  home_form_edit_heading: "Edit project",
  home_field_name: "Name",
  home_field_code: "Code",
  home_field_client: "Client",
  home_field_site_address: "Site address",
  home_field_district: "District",
  home_field_building_type: "Building type",
  home_field_storeys: "Storeys",
  home_field_gfa: "Target GFA (m²)",
  home_field_gfa_hint: "Stored in square metres — the square-feet equivalent shows as you type.",
  home_field_notes: "Notes",
  // The enum value travels in the hidden input; the label is prose (I-33).
  home_building_type_residential: "Residential",
  home_building_type_commercial: "Commercial",
  home_building_type_mixed: "Mixed",
  home_building_type_industrial: "Industrial",
  home_building_type_infrastructure: "Infrastructure",
  home_form_submit_create: "Create project",
  home_form_submit_save: "Save changes",
  home_form_cancel: "Cancel",
  home_form_name_refusal: "A project name needs at least one visible character — nothing was saved.",
  home_form_type_refusal: "Choose a building type — nothing was saved.",
  home_form_number_refusal: "Storeys and target GFA need plain numbers — nothing was saved.",
  home_status_active: "Active",
  home_status_archived: "Archived",
  // The date is data, filled by the string seam (I-37).
  home_project_updated: "Updated {date}",
  home_project_ruleset: "View rule set",
  home_stat_sheets: "Sheets",
  home_stat_campaigns: "Campaigns",
  home_stat_estimates: "Estimates",
  home_stat_bids: "Bids",
  home_project_edit: "Edit",
  home_project_archive: "Archive",
  home_project_restore: "Restore",
  home_documents_heading: "Recent documents",
  home_documents_empty: "Issued documents appear here once your projects produce them — nothing has been issued yet.",
  home_evidence_projects: "Go to Projects",
} as const;
