// R-SPINE-060: the measurement's own table. R-UI-024's timeline names every kind SEAM-JOBS runs, so
// the kind that measures a campaign owes the word a person reads it as — a step that named no work
// would be a process somebody is watching without being told what it is.
//
// S-Measure's words follow, block by block in the order its slices land them, fixed verbatim by
// docs/design/s-measure.md § 4: the armed tools (S4) first. Figures and units arrive through the
// format seam; the unit glyph a figure is read in stands beside the slot, as the snapping readout's
// "{metres} m" does.
export const measure = {
  job_step_measure: "Measure the pinned drawings",

  // S4 — the tool row's menu, the preconditions said before the first click, the stage and the
  // status line's measure cell, and the hidden line's announcements (s-measure § 2.1–2.4, § 3).
  measure_tool_rectangle: "Rectangle",
  measure_tool_cutout: "Cut out",
  measure_tool_perimeter: "Perimeter",
  measure_tool_volume: "Volume",
  measure_tool_typical: "Typical ×n",
  measure_tool_pitch: "Pitch multiplier",
  measure_tool_layer_region: "Select on layer in region",
  measure_tool_fill: "Fill a closed region",
  measure_tool_freehand: "Freehand",
  measure_tool_not_yet: "Arrives with the rest of the manual toolset",
  measure_tools_offline: "You are offline. You can draw, and confirm when the connection returns.",
  measure_tools_permission: "Measuring needs the Measure permission. A project principal can give you a role that carries it.",
  viewer_status_measure: "Measure",
  measure_status_tool: "{tool} · {points} points",
  measure_status_tool_one: "{tool} · 1 point",
  measure_status_pick_in_select: "Distances are picked in Select: press V, then Alt+click.",
  measure_status_finish_first: "Finish or discard this outline first (Enter or Escape)",
  measure_status_cutout_outside: "A cut-out must stand inside the outline and clear of the other cut-outs",
  measure_status_too_few: "{tool} needs {count} points before it can be finished.",
  measure_status_degenerate: "This outline encloses nothing: it crosses itself, or its points stand in one line.",
  measure_status_repeated: "A point already stands there.",
  measure_status_unrecorded: "Measured, not recorded: no condition is picked.",
  measure_view_unscaled: "This view has no scale of record. Affirm its scale in the Scale tab, then measure here.",
  measure_figure_uncalibrated: "drawing units: this view has no scale of record",
  measure_figure_windowed: "sheet units: this shape does not stand inside one viewport",
  measure_figure_unrecorded: "sheet units: a two-point scale is not carried through a viewport",
  measure_figure_length: "L {value} m",
  measure_figure_area: "A {value} m²",
  measure_figure_segment: "+ {value} m",
  measure_figure_count: "N {value}",
  measure_figure_length_units: "L {value}",
  measure_figure_area_units: "A {value}",
  measure_figure_segment_units: "+ {value}",
  measure_point_placed: "Point {n} placed, {basis}.",
  measure_point_removed: "Last point removed.",
  measure_shape_finished: "{tool} finished: {figure}.",
  measure_shape_reopened: "Open again: add points, or press Enter to close it.",
  measure_cutout_started: "Cutting out: place the cut-out's points inside the outline, then press Enter.",
  measure_cutout_finished: "Cut out: {figure} remains.",
  measure_cutout_discarded: "Cut-out discarded. The outline stands.",
  measure_draft_kept: "Nothing was committed. Your outline is still on the sheet: press Enter to open it again, or Escape to discard it.",
  measure_draft_discarded: "Measurement discarded.",
  // R-UI-060: the keyboard way to a measurement, named beside the sheet with the camera's keys.
  measure_canvas_keys:
    "L, A and C arm Linear, Area and Count. Space places a point at the cursor the arrow keys move, Enter finishes, Backspace removes the last point, X cuts out and Escape discards.",

  // S5 — the condition chest in the drawer and its New condition popover (s-measure § 2.6, § 3, § 4).
  measure_chest_heading: "Conditions",
  measure_chest_new: "New condition",
  measure_chest_empty_title: "No conditions yet",
  measure_chest_empty_body: "A condition is what you measure: a name, a class, a kind and its sizes. 75 CC blinding under SOG is a slab blinded 75 mm thick.",
  measure_chest_empty_action: "New condition",
  measure_chest_readonly: "Read-only: your role does not carry the Measure permission.",
  measure_chest_row_label: "{condition}: pick it and arm {tool}",
  measure_chest_row_menu: "More for {condition}",
  measure_chest_total_none: "—",
  measure_chest_total_label: "{measured} measured in this campaign, {billed} billed",
  measure_chest_read_failed: "The conditions could not be read.",
  measure_read_report: "Report {id}",
  measure_retry: "Try again",
  measure_status_drawing: "{tool} · {condition} · {points} points",
  measure_status_condition_pending: "Measured under {condition}. Confirming a measurement arrives with its card; nothing is recorded yet.",
  measure_condition_name: "Name",
  measure_condition_geometry: "Measured as",
  measure_condition_geometry_area: "Area",
  measure_condition_geometry_length: "Length",
  measure_condition_geometry_count: "Count",
  measure_condition_class: "Class",
  measure_condition_kinds: "Kinds",
  measure_condition_none_offered: "Nothing is measured by hand this way yet.",
  measure_condition_reading_t: "Thickness",
  measure_condition_reading_unit: "{reading} unit",
  measure_condition_colour: "Colour",
  measure_condition_hatch: "Hatch",
  measure_condition_hatch_solid: "Solid tint",
  measure_condition_hatch_diagonal: "Diagonal",
  measure_condition_hatch_cross: "Cross",
  measure_condition_hatch_dots: "Dots",
  measure_condition_hatch_horizontal: "Horizontal",
  measure_condition_hatch_vertical: "Vertical",
  measure_condition_hotkey: "Hotkey",
  measure_condition_hotkey_none: "None: the digits pick the chest's first nine",
  measure_condition_save: "Save condition",
  measure_condition_cancel: "Cancel",
  measure_condition_retire: "Remove from chest",
} as const;
