// This screen's copy, fixed verbatim by docs/design/s-drawings.md § 3 (the s-settings-ruleset I-24
// precedent: copy lives beside the page it is written for, keyed, never inline in JSX).
//
// Enum values, formats, schemes and entity keys are data and render verbatim as data (I-25's class),
// so no sentence here weaves one in; the registered refusals' own words belong to the register.
export const drawings = {
  drawings_heading: "Drawings",
  drawings_caption: "Every sheet this project holds, as the extractor read it. A sheet is measured only after its discipline is confirmed.",
  drawings_upload_heading: "Add drawings",
  drawings_upload_hint: "A stored drawing is read straight away. The steps below report how far that has got.",
  drawings_timeline_heading: "Reading drawings",
  drawings_timeline_idle: "No drawing is being read right now.",
  drawings_step_ingest: "Read the drawing",
  drawings_step_thumbnails: "Draw the sheet previews",
  drawings_step_probe: "Check the worker",
  drawings_status_queued: "Queued",
  drawings_status_running: "Running",
  drawings_status_succeeded: "Done",
  drawings_status_failed: "Failed",
  drawings_status_refused: "Refused",
  drawings_timeline_seconds: "{seconds} s",
  drawings_timeline_transport_lost: "Live progress stopped arriving. Reload the page to see where these jobs stand.",
  drawings_sheets_heading: "Sheets",
  drawings_sheets_hint: "Sheet numbers, titles and disciplines are read from each title block. Confirm a discipline from a group the product offers — there is no select-all.",
  drawings_search_label: "Search sheets",
  drawings_filter_legend: "Discipline",
  drawings_filter_all: "All disciplines",
  drawings_sheet_count: "{shown} of {total} sheets",
  drawings_groups_hint: "Confirmation is offered as groups the product names. A group is confirmed exactly as it is named.",
  drawings_group_label_discipline: "{discipline} proposed from the title block on {subject}",
  drawings_group_label_sheet: "{discipline} proposed for {subject}",
  drawings_group_count: "{count} sheets",
  drawings_thumbnail_alt: "Sheet preview of {sheet}",
  drawings_thumbnail_pending: "Preview not drawn yet",
  drawings_number_none: "No sheet number",
  drawings_format_label: "File format {value}",
  drawings_scheme_label: "Source scheme {value}",
  drawings_basis_grammar: "Read from the title block",
  drawings_basis_none: "No title-block text to read",
  drawings_basis_confirmed: "Confirmed",
  drawings_cited_label: "Cited entities",
  drawings_scale_unaffirmed: "Scale not affirmed",
  drawings_scale_affirmed: "Scale affirmed",
  drawings_scale_unplaceable: "Scale unplaceable — this layout carries no extent or no drawing units",
  drawings_views_unclassified: "Views not classified yet",
  drawings_views_count: "{count} views",
  drawings_fact_strays_rejected: "Strays rejected",
  drawings_fact_explode_truncated: "Explode truncated",
  drawings_fact_explode_losses: "Explode losses",
  drawings_fact_flatten_capped: "Flatten capped",
  drawings_fact_dropped_layouts: "Dropped layouts",
  drawings_fact_yes: "yes",
  drawings_fact_no: "no",
  drawings_confirm_legend: "Discipline to confirm",
  drawings_sheet_confirm: "Preview this confirmation",
  drawings_confirm_pending: "Working out what this confirmation would do…",
  drawings_confirm_committed: "Recorded. Those sheets now carry a confirmed discipline.",
  drawings_empty_no_drawings_heading: "No drawings yet",
  drawings_empty_no_drawings_body: "Add a drawing above; its sheets appear here as soon as it has been read.",
  drawings_empty_awaiting_heading: "No sheets read yet",
  drawings_empty_awaiting_body: "This project holds drawings that have not been read through. Each one's sheets appear here as it finishes.",
  drawings_empty_no_match_heading: "No sheet matches this search",
  drawings_empty_no_match_search: "No sheet's title or number contains {search}.",
  drawings_empty_no_match_discipline: "No sheet stands as {discipline}.",
  drawings_empty_no_match_both: "No sheet stands as {discipline} with a title or number containing {search}.",
  drawings_empty_no_match_body: "Every sheet stays in the index — clear the search or choose All disciplines to see the rest.",
  drawings_empty_clear: "Clear search and filter",
  drawings_offline: "The connection to the product is gone. An upload already running continues when it returns, and nothing can be confirmed until then.",
  drawings_offline_notice: "Nothing was previewed: the connection to the product is gone.",
  drawings_denied_permission: "Confirming a sheet's discipline needs the MEASURE permission on this project, and your account does not hold it.",
  drawings_denied_holder: "This project's principals and measurers hold it; a principal grants it on the participants screen.",
  drawings_evidence_participants: "Open the project's participants",
  drawings_evidence_reload: "Reload the sheet index",
  drawings_evidence_upload_again: "Add the drawing again",
} as const;
