/**
 * C-06 / AM-02 — the complete toolchain surface in one reviewed unit, and
 * nothing else riding along with it.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const at = (relative: string): string => path.join(ROOT, relative);

/** Every file C-06 names, as the spec's interfaces list them. */
const TOOLCHAIN_SURFACE = [
  '.nvmrc',
  '.gitignore',
  'package.json',
  'pnpm-lock.yaml',
  'tsconfig.json',
  'eslint.config.mjs',
  'vitest.config.ts',
  'playwright.config.ts',
  'drizzle.config.ts',
  'scripts/verify.mjs',
  'scripts/checkup.mjs',
  'scripts/db-migrate.mjs',
  'scripts/db-drift.mjs',
  'scripts/method-hashes.mjs',
  'scripts/e2e.mjs',
  'scripts/seed.mjs',
  'scripts/gen-fixtures.mjs',
  'scripts/traceability.mjs',
  '.github/workflows/ci.yml',
  'cad/pyproject.toml',
  'cad/uv.lock',
  'fixtures/gen/README.md',
  'docs/toolchain.md',
] as const;

/** AM-02: tokens, primitives, the shell and auth are later increments. */
const OUT_OF_SCOPE_ROOTS = ['src', 'db', 'documents', 'tests/e2e'] as const;

describe('C-06 the toolchain is delivered whole', () => {
  it('C-06: every file the increment declares is present', () => {
    const missing = TOOLCHAIN_SURFACE.filter((relative) => !existsSync(at(relative)));
    expect(missing, 'toolchain files missing from the tree').toEqual([]);
  });

  it('C-06: eslint-rules/ carries the local cubit plugin', () => {
    const dir = at('eslint-rules');
    expect(existsSync(dir), 'eslint-rules/ is missing').toBe(true);
    const modules = readdirSync(dir).filter((name) => name.endsWith('.mjs'));
    expect(modules.length, 'eslint-rules/ has no .mjs rule modules').toBeGreaterThan(0);
  });

  it('C-06/AM-02: the toolchain lands without any product code beside it', () => {
    // Red today because the surface above does not exist; the second half is
    // the named regression guard that keeps AM-02's scope honest.
    const missing = TOOLCHAIN_SURFACE.filter((relative) => !existsSync(at(relative)));
    expect(missing, 'toolchain files missing from the tree').toEqual([]);
    const strayProductCode = OUT_OF_SCOPE_ROOTS.filter((relative) => existsSync(at(relative)));
    expect(strayProductCode, 'increment zero is the toolchain only (AM-02)').toEqual([]);
  });

  it('C-10: docs/traceability.json is generated by the gate, never committed here', () => {
    // Red today via the script requirement; the absence check is the guard.
    expect(existsSync(at('scripts/traceability.mjs')), 'scripts/traceability.mjs is missing').toBe(
      true,
    );
    expect(
      existsSync(at('docs/traceability.json')),
      'docs/traceability.json is gate-owned and must not be committed by this increment',
    ).toBe(false);
  });
});
