#!/usr/bin/env node
/**
 * pnpm gen:tokens — R-UI-001. Emits `src/ui/tokens.ts` as CSS variables into the
 * generated block of `src/app/globals.css`: the palette and geometry on `:root`,
 * then the role variables once per theme (`:root` for light, `[data-theme="dark"]`
 * for dark).
 *
 * Idempotent by construction: everything outside the sentinels is left alone, so
 * the unit test can assert that the committed block equals a fresh emission.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = new URL('..', import.meta.url);
const GLOBALS = fileURLToPath(new URL('src/app/globals.css', ROOT));

const START = '/* cubit:tokens:start — generated by `pnpm gen:tokens`; edit src/ui/tokens.ts */';
const END = '/* cubit:tokens:end */';

const { tokens } = await import(new URL('src/ui/tokens.ts', ROOT).href);

const kebab = (name) => String(name).replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** @param {Array<[string, string|number]>} pairs */
const declare = (pairs, indent = '  ') =>
  pairs.map(([name, value]) => `${indent}--${name}: ${value};`).join('\n');

function palette() {
  const out = [];

  for (const [step, value] of Object.entries(tokens.graphite)) out.push([`graphite-${step}`, value]);
  for (const [step, value] of Object.entries(tokens.cobalt)) out.push([`cobalt-${step}`, value]);

  for (const [name, entry] of Object.entries(tokens.semantic)) {
    out.push([`semantic-${name}`, entry.base]);
    out.push([`semantic-${name}-on-dark`, entry.onDark]);
    out.push([`semantic-${name}-surface`, entry.surface]);
    out.push([`semantic-${name}-surface-dark`, entry.surfaceDark]);
  }

  for (const [name, entry] of Object.entries(tokens.basis)) {
    out.push([`basis-${kebab(name)}`, entry.colour]);
    out.push([`basis-${kebab(name)}-glyph`, `'${entry.glyph}'`]);
  }

  for (const [name, value] of Object.entries(tokens.canvas)) out.push([`canvas-${kebab(name)}`, value]);
  for (const [name, value] of Object.entries(tokens.elementClass)) out.push([`element-${kebab(name)}`, value]);

  for (const [name, value] of Object.entries(tokens.spacing)) out.push([`space-${name}`, `${value}px`]);
  for (const [name, value] of Object.entries(tokens.radii)) out.push([`radius-${name}`, `${value}px`]);
  for (const [name, value] of Object.entries(tokens.elevation)) out.push([`shadow-${name}`, value]);

  for (const [name, value] of Object.entries(tokens.type.families)) out.push([`font-${name}`, value]);
  for (const [name, value] of Object.entries(tokens.type.scale)) out.push([`text-${kebab(name)}`, `${value}px`]);
  for (const [name, value] of Object.entries(tokens.type.weight)) out.push([`weight-${name}`, value]);
  for (const [name, value] of Object.entries(tokens.type.lineHeight)) out.push([`leading-${name}`, value]);

  for (const [name, value] of Object.entries(tokens.motion.duration)) out.push([`duration-${kebab(name)}`, `${value}ms`]);
  for (const [name, value] of Object.entries(tokens.motion.easing)) out.push([`ease-${kebab(name)}`, value]);

  for (const [name, value] of Object.entries(tokens.z)) out.push([`z-${kebab(name)}`, value]);
  for (const [name, value] of Object.entries(tokens.breakpoints)) out.push([`bp-${name}`, `${value}px`]);

  return out;
}

function roles(theme) {
  return Object.entries(tokens.themes[theme]);
}

function block() {
  return [
    START,
    ':root {',
    declare(palette()),
    '',
    '  /* roles — light */',
    declare(roles('light')),
    '}',
    '',
    '[data-theme="dark"] {',
    '  color-scheme: dark;',
    declare(roles('dark')),
    '}',
    END,
  ].join('\n');
}

const source = readFileSync(GLOBALS, 'utf8');
const from = source.indexOf(START);
const to = source.indexOf(END);
if (from === -1 || to === -1) {
  console.error(`gen:tokens: ${GLOBALS} is missing the cubit:tokens sentinels`);
  process.exit(1);
}

const next = source.slice(0, from) + block() + source.slice(to + END.length);
if (next === source) {
  console.log('gen:tokens: globals.css is already at the emission');
} else {
  writeFileSync(GLOBALS, next);
  console.log(`gen:tokens: wrote ${palette().length + roles('light').length + roles('dark').length} CSS variables`);
}
