# Generated by Django 6.1.1 on 2026-09-28 10:48, then row-level security added by hand (ticket 08;
# docs/data-model.md §2 and §3.1): run as the owner.
#
# - Every projects table has row-level security ENABLED, never forced, and its own-tenant policy for
#   reads and writes alike, with no widening: a Project, its Site and its Buildings are their
#   Developer's only.
# - Composite keys hold a Site and a Building to a Project of their own tenant.
# - vextrus_app's rights come from platform's default privileges (platform 0003): select, insert,
#   update and delete, never TRUNCATE; UPDATE is then narrowed to the columns a person may change,
#   so the app cannot UPDATE a Project's Market or currency, nor move a Site or a Building to
#   another Project by UPDATE.
# - A trigger holds a Project to its Developer's Market on every INSERT and UPDATE, whoever writes:
#   its market_id is the Developer's Market, its currency that Market's, its unit system one that
#   Market offers. So the app cannot swap them by deleting a Project and inserting it again either
#   (the staff flag's hole in 02 was "by UPDATE, then by INSERT"; session 03's lessons). Its function
#   is owned by vextrus, SECURITY DEFINER with search_path pinned, so it reads the Developer and its
#   Market whatever the tenant settings say: the one place projects reads platform's tables, for
#   integrity only, never for data.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import vextrus.platform.ids

OWN_TENANT = "tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid"

TABLES = ("projects_project", "projects_site", "projects_building")

POLICIES = [
    *(f"alter table {table} enable row level security" for table in TABLES),
    *(f"create policy own_tenant on {table} using ({OWN_TENANT})" for table in TABLES),
]
POLICIES_REVERSE = [
    *(f"drop policy own_tenant on {table}" for table in TABLES),
    *(f"alter table {table} disable row level security" for table in TABLES),
]

APP = settings.VEXTRUS_APP_ROLE

GRANTS = [
    f"revoke update on {table} from {APP}" for table in TABLES
] + [
    f"grant update (code, code_key, name, address, unit_system) on projects_project to {APP}",
    f"grant update (name) on projects_site to {APP}",
    f"grant update (code, name, ordinal) on projects_building to {APP}",
]
GRANTS_REVERSE = [
    f"revoke update on {table} from {APP}" for table in TABLES
] + [f"grant update on {table} to {APP}" for table in TABLES]

FOLLOWS_MARKET = [
    """
    create function public.projects_project_follows_market()
    returns trigger
    language plpgsql security definer
    set search_path = pg_catalog, pg_temp
    as $$
    declare
      market record;
    begin
      select m.id, m.currency_code, m.unit_systems into market
        from public.platform_developer d
        join public.platform_market m on m.id = d.market_id
       where d.id = new.tenant_id and not d.is_library;
      if not found then
        raise exception 'projects_project_follows_market: % is not a Developer', new.tenant_id
          using errcode = 'check_violation';
      end if;
      if new.market_id is distinct from market.id
         or new.currency_code is distinct from market.currency_code
         or not (market.unit_systems ? new.unit_system) then
        raise exception 'projects_project_follows_market: a Project takes its Developer''s Market, '
                        'its currency and one of its unit systems'
          using errcode = 'check_violation';
      end if;
      return new;
    end
    $$
    """,
    "revoke all on function public.projects_project_follows_market() from public",
    """
    create trigger projects_project_follows_market
      before insert or update of tenant_id, market_id, currency_code, unit_system
      on projects_project
      for each row execute function public.projects_project_follows_market()
    """,
]
FOLLOWS_MARKET_REVERSE = [
    "drop trigger projects_project_follows_market on projects_project",
    "drop function public.projects_project_follows_market()",
]

KEYS = [
    f"""alter table {table} add constraint {table}_own_tenant
         foreign key (tenant_id, project_id) references projects_project (tenant_id, id)
         on delete cascade deferrable initially deferred"""
    for table in ("projects_site", "projects_building")
]
KEYS_REVERSE = [
    f"alter table {table} drop constraint {table}_own_tenant"
    for table in ("projects_building", "projects_site")
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Its default privileges give vextrus_app its rights on these tables; the trigger reads
        # its Developers and Markets.
        ("platform", "0003_row_level_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("code", models.CharField(max_length=32)),
                (
                    "code_key",
                    models.CharField(
                        editable=False,
                        help_text="The code folded (NFKC, then case-folded), unique in the Developer.",
                        max_length=128,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("market_id", models.UUIDField(editable=False)),
                (
                    "currency_code",
                    models.CharField(
                        editable=False, help_text="ISO 4217.", max_length=3
                    ),
                ),
                ("unit_system", models.CharField(max_length=16)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "code_key"),
                        name="projects_project_code_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("tenant_id", "id"), name="projects_project_tenant_id"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("code", ""), _negated=True),
                            models.Q(("name", ""), _negated=True),
                        ),
                        name="projects_project_code_and_name",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=200)),
                ("ordinal", models.PositiveSmallIntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "project", "code"),
                        name="projects_building_code_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("tenant_id", "project", "ordinal"),
                        name="projects_building_ordinal_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "project",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "project"), name="projects_site_one"
                    )
                ],
            },
        ),
        migrations.RunSQL(POLICIES, POLICIES_REVERSE),
        migrations.RunSQL(KEYS, KEYS_REVERSE),
        migrations.RunSQL(GRANTS, GRANTS_REVERSE),
        migrations.RunSQL(FOLLOWS_MARKET, FOLLOWS_MARKET_REVERSE),
    ]
