# Generated by Django 6.1.1 on 2026-09-29, then row-level security, the same-tenant keys, the reach
# triggers and vextrus_app's rights written by hand (ticket 14; docs/data-model.md §2 and §3.2). Run as
# the owner.
#
# - Every drawings table has row-level security ENABLED, never forced, and its own-tenant policy for
#   reads and writes alike. `drawings_discipline` is a Library table: it adds one FOR SELECT policy
#   admitting the acting tenant's Market Library through app.library_id, so a Developer reads its
#   Market's Disciplines and writes none (vextrus_app may only SELECT it; sync_library writes it as
#   the owner). No policy holds a join, a sub-select or any other function call.
# - A reference inside drawings names a row of the same tenant: a composite key on (tenant_id, x_id)
#   beside Django's own, deferred, as projects' keys are; and a reference between two rows of one
#   Drawing Set names a row of the same set, (tenant_id, drawing_set_id, x_id), so a printed sheet,
#   its Sheet, its file, its Revision and its Plot's PDF, a file and its Revision, a state and its
#   map rows are all of one set: no write crosses Projects inside one Developer.
# - What a key cannot hold, a trigger does, whoever writes, on INSERT and on UPDATE, so neither a
#   chosen id nor deleting a row and inserting it again gets round it. Each trigger function runs as
#   its caller (not SECURITY DEFINER), so its lookups see only what the writer's own policies admit;
#   the owner sees every row and passes. They read projects' and platform's tables for integrity
#   only, as projects' own trigger reads platform's:
#     - a Discipline named by a file, a Revision, a Sheet or a View is one the writer can read: its
#       own Market's (another Market's Library is not);
#     - a Drawing Set's Project is the writer's own;
#     - a file's original is a StoredFile of the writer's, of the set's Project, with the file's
#       sha256 and size; its Building is one of the set's Project; its Revision is of its own
#       Discipline;
#     - a kept ReadArtefact is a StoredFile of the set's Project derived from the file's sha256;
#     - a Sheet's Building is one of the set's Project; a printed sheet's Sheet is of its file's
#       Building (a reading may point it at another Sheet, never across Buildings); its render a
#       StoredFile of the set's Project;
#     - a view's predecessor is a view of its own Drawing Set.
# - vextrus_app's rights come from platform's default privileges (platform 0003): select, insert,
#   update and delete, never TRUNCATE. Then narrowed: the Disciplines it may only read; a read job's
#   steps and a kept ReadArtefact it may only add (never change or delete); a file it may never
#   delete, and may UPDATE only its reading's columns (never its contents' sha256, its original, its
#   name, its set or its Building); a set only its name and current state, and never delete; a
#   state only its status and reader; a Revision it never updates or deletes (a first issue left
#   with no file stays, and is found again by its Discipline's next file); a Sheet never moves to
#   another set, Building, source file or place, nor a printed sheet to another set, source file or
#   place; a view only takes a decision (a reading replaces views, never moves one); a state's map
#   row is never updated. Since a file is never deleted by the app and its steps' key to it takes
#   no action, its steps cannot be removed with it either.
# - A reading's own rows the app may delete (a Sheet, a printed sheet, a view, a map row: a reading
#   again replaces them), so the keys naming a Sheet, a printed sheet or a view RESTRICT, never
#   deferred (IMMEDIATE): a row something still names cannot be deleted, even to come back under its
#   id in the same statement, so never made again in another set, Building or place with what names
#   it following.
# - Those rows' ids are named outside drawings too (takeoff's Coverage, placements and Traces), and
#   a row nothing in drawings names may still be deleted: so each of their ids is written to
#   drawings_usedid (insert-only for the app) at its row's insert, and an id found there is refused,
#   whatever was deleted first and even within one statement. An id, once used, never comes back.
# - Held by projects, not here: a Building's Project. A Building is named by id (a downward id), and
#   the triggers check it at each write of a drawings row; projects' own rights decide whether a
#   Building can move to another Project afterwards (vextrus_app may today delete a Building and
#   insert it again: projects' rule, reported to its owner).

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import vextrus.platform.ids

APP = settings.VEXTRUS_APP_ROLE

OWN_TENANT = "tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid"
LIBRARY = "tenant_id = nullif(current_setting('app.library_id', true), '')::uuid"

LIBRARY_TABLES = ("drawings_discipline",)
TENANT_TABLES = (
    "drawings_drawingset",
    "drawings_drawingsetstate",
    "drawings_revision",
    "drawings_drawingfile",
    "drawings_artefact",
    "drawings_readstep",
    "drawings_sheet",
    "drawings_sheetrevision",
    "drawings_statesheet",
    "drawings_view",
    "drawings_usedid",
)
TABLES = LIBRARY_TABLES + TENANT_TABLES

POLICIES = [
    *(f"alter table {table} enable row level security" for table in TABLES),
    *(f"create policy own_tenant on {table} using ({OWN_TENANT})" for table in TABLES),
    *(
        f"create policy library_reads on {table} for select using ({LIBRARY})"
        for table in LIBRARY_TABLES
    ),
]
POLICIES_REVERSE = [
    *(f"drop policy library_reads on {table}" for table in LIBRARY_TABLES),
    *(f"drop policy own_tenant on {table}" for table in TABLES),
    *(f"alter table {table} disable row level security" for table in TABLES),
]

# Each reference inside drawings: (table, its columns, the table it names, their columns). A row names
# one of its own tenant (tenant_id, x_id); a row of a Drawing Set names one of the same set
# (tenant_id, drawing_set_id, x_id), so no write crosses Projects inside one Developer either.
TENANT = ("tenant_id", "id")
SET = ("tenant_id", "drawing_set_id", "id")
REFERENCES = (
    ("drawings_drawingset", ("tenant_id", "id", "current_state_id"), "drawings_drawingsetstate", SET),
    ("drawings_drawingsetstate", ("tenant_id", "drawing_set_id"), "drawings_drawingset", TENANT),
    ("drawings_drawingsetstate", ("tenant_id", "drawing_set_id", "revision_id"), "drawings_revision", SET),
    (
        "drawings_drawingsetstate",
        ("tenant_id", "drawing_set_id", "parent_state_id"),
        "drawings_drawingsetstate",
        SET,
    ),
    ("drawings_revision", ("tenant_id", "drawing_set_id"), "drawings_drawingset", TENANT),
    ("drawings_drawingfile", ("tenant_id", "drawing_set_id"), "drawings_drawingset", TENANT),
    ("drawings_drawingfile", ("tenant_id", "drawing_set_id", "revision_id"), "drawings_revision", SET),
    ("drawings_artefact", ("tenant_id", "file_id"), "drawings_drawingfile", TENANT),
    ("drawings_readstep", ("tenant_id", "file_id"), "drawings_drawingfile", TENANT),
    ("drawings_sheet", ("tenant_id", "drawing_set_id"), "drawings_drawingset", TENANT),
    ("drawings_sheet", ("tenant_id", "drawing_set_id", "source_file_id"), "drawings_drawingfile", SET),
    ("drawings_sheetrevision", ("tenant_id", "drawing_set_id"), "drawings_drawingset", TENANT),
    ("drawings_sheetrevision", ("tenant_id", "drawing_set_id", "sheet_id"), "drawings_sheet", SET),
    ("drawings_sheetrevision", ("tenant_id", "drawing_set_id", "revision_id"), "drawings_revision", SET),
    (
        "drawings_sheetrevision",
        ("tenant_id", "drawing_set_id", "source_file_id"),
        "drawings_drawingfile",
        SET,
    ),
    (
        "drawings_sheetrevision",
        ("tenant_id", "drawing_set_id", "plot_file_id"),
        "drawings_drawingfile",
        SET,
    ),
    ("drawings_statesheet", ("tenant_id", "drawing_set_id"), "drawings_drawingset", TENANT),
    ("drawings_statesheet", ("tenant_id", "drawing_set_id", "state_id"), "drawings_drawingsetstate", SET),
    (
        "drawings_statesheet",
        ("tenant_id", "drawing_set_id", "sheet_revision_id"),
        "drawings_sheetrevision",
        SET,
    ),
    ("drawings_view", ("tenant_id", "sheet_revision_id"), "drawings_sheetrevision", TENANT),
    ("drawings_view", ("tenant_id", "predecessor_view_id"), "drawings_view", TENANT),
)


def _key_name(table: str, columns: tuple[str, ...]) -> str:
    kind = "own_set" if len(columns) == 3 else "own_tenant"
    return f"{table}_{columns[-1].removesuffix('_id')}_{kind}"[:63]


IMMEDIATE = {
    ("drawings_sheetrevision", ("tenant_id", "drawing_set_id", "sheet_id")),
    ("drawings_statesheet", ("tenant_id", "drawing_set_id", "sheet_revision_id")),
    ("drawings_view", ("tenant_id", "sheet_revision_id")),
    ("drawings_view", ("tenant_id", "predecessor_view_id")),
}
"""The keys naming a Sheet, a printed sheet or a view, which the app may delete: RESTRICT, never
deferred, so a row something still names cannot be deleted, not even to be inserted again under its
id in the same statement (a NO ACTION key, even immediate, lets a row whose key is back by the
statement's end pass), nor made again elsewhere with what names it following."""


def _timing(table: str, columns: tuple[str, ...]) -> str:
    if (table, columns) in IMMEDIATE:
        return "on delete restrict on update restrict not deferrable"
    return "deferrable initially deferred"


KEYS = [
    f"""alter table {table} add constraint {_key_name(table, columns)}
          foreign key ({", ".join(columns)}) references {target} ({", ".join(target_columns)})
          {_timing(table, columns)}"""
    for table, columns, target, target_columns in REFERENCES
]
KEYS_REVERSE = [
    f"alter table {table} drop constraint {_key_name(table, columns)}"
    for table, columns, _target, _target_columns in reversed(REFERENCES)
]

# Each trigger: (function, table, the columns whose change fires it, the checks, each a condition the
# new row must meet and what the refusal says). Every refusal is errcode 42501, as live_model's are.
IN_REACH = "exists (select 1 from public.drawings_discipline d where d.id = new.{column})"
SET_PROJECT = "(select s.project_id from public.drawings_drawingset s where s.id = new.drawing_set_id)"
SHEET_SET = "(select h.drawing_set_id from public.drawings_sheet h where h.id = new.sheet_id)"
CHECKS = (
    (
        "drawings_revision_in_reach",
        "drawings_revision",
        ("tenant_id", "discipline_id"),
        ((IN_REACH.format(column="discipline_id"), "names a Discipline of another Market"),),
    ),
    (
        "drawings_drawingset_in_reach",
        "drawings_drawingset",
        ("tenant_id", "project_id"),
        (
            (
                "exists (select 1 from public.projects_project p where p.id = new.project_id)",
                "names a Project that is not this Developer's",
            ),
        ),
    ),
    (
        "drawings_drawingfile_in_reach",
        "drawings_drawingfile",
        (
            "tenant_id",
            "drawing_set_id",
            "revision_id",
            "discipline_id",
            "building_id",
            "stored_file_id",
            "sha256",
        ),
        (
            (
                "new.discipline_id is null or " + IN_REACH.format(column="discipline_id"),
                "names a Discipline of another Market",
            ),
            (
                (
                    "new.revision_id is null or exists (select 1 from public.drawings_revision r"
                    " where r.id = new.revision_id and r.discipline_id = new.discipline_id)"
                ),
                "names a Revision of another Discipline",
            ),
            (
                (
                    "new.building_id is null or exists (select 1 from public.projects_building b"
                    f" where b.id = new.building_id and b.project_id = {SET_PROJECT})"
                ),
                "names a Building of another Project",
            ),
            (
                (
                    "exists (select 1 from public.platform_storedfile o"
                    " where o.id = new.stored_file_id"
                    " and o.tenant_id = new.tenant_id and o.kind = 'original'"
                    f" and o.project_id = {SET_PROJECT}"
                    " and o.sha256 = new.sha256 and o.size = new.size)"
                ),
                "names an original that is not its own contents",
            ),
        ),
    ),
    (
        "drawings_artefact_in_reach",
        "drawings_artefact",
        ("tenant_id", "file_id", "stored_file_id"),
        (
            (
                (
                    "exists (select 1 from public.platform_storedfile o"
                    " join public.drawings_drawingfile f on f.id = new.file_id"
                    " join public.drawings_drawingset s on s.id = f.drawing_set_id"
                    " where o.id = new.stored_file_id and o.tenant_id = new.tenant_id"
                    " and o.kind = 'derived' and o.project_id = s.project_id"
                    " and o.source_sha256 = f.sha256)"
                ),
                "names a kept file not derived from this file",
            ),
        ),
    ),
    (
        "drawings_sheet_in_reach",
        "drawings_sheet",
        ("tenant_id", "drawing_set_id", "discipline_id", "building_id"),
        (
            (
                "new.discipline_id is null or " + IN_REACH.format(column="discipline_id"),
                "names a Discipline of another Market",
            ),
            (
                (
                    "new.building_id is null or exists (select 1 from public.projects_building b"
                    f" where b.id = new.building_id and b.project_id = {SET_PROJECT})"
                ),
                "names a Building of another Project",
            ),
        ),
    ),
    (
        "drawings_sheetrevision_in_reach",
        "drawings_sheetrevision",
        ("tenant_id", "sheet_id", "source_file_id", "render_file_id"),
        (
            (
                (
                    "exists (select 1 from public.drawings_sheet h join public.drawings_drawingfile f"
                    " on f.id = new.source_file_id where h.id = new.sheet_id"
                    " and h.building_id is not distinct from f.building_id)"
                ),
                "names a Sheet of another Building than its file's",
            ),
            (
                (
                    "new.render_file_id is null or exists (select 1 from public.platform_storedfile o"
                    f" join public.drawings_drawingset s on s.id = {SHEET_SET} where"
                    " o.id = new.render_file_id and o.tenant_id = new.tenant_id"
                    " and o.kind = 'derived' and o.project_id = s.project_id)"
                ),
                "names a render that is not a kept file of its Project",
            ),
        ),
    ),
    (
        "drawings_view_in_reach",
        "drawings_view",
        ("tenant_id", "part_id", "predecessor_view_id", "sheet_revision_id"),
        (
            (
                "new.part_id is null or " + IN_REACH.format(column="part_id"),
                "names a Discipline of another Market",
            ),
            (
                (
                    "new.predecessor_view_id is null or exists (select 1 from public.drawings_view p"
                    " join public.drawings_sheetrevision pr on pr.id = p.sheet_revision_id"
                    " join public.drawings_sheetrevision nr on nr.id = new.sheet_revision_id"
                    " where p.id = new.predecessor_view_id and pr.drawing_set_id = nr.drawing_set_id)"
                ),
                "names a view of another Drawing Set",
            ),
        ),
    ),
)


def _trigger(function, table, columns, checks):
    """A trigger function run as its caller, so its lookups see only what the writer's policies
    admit (the owner sees every row and passes)."""
    body = "\n".join(
        f"""      if not ({condition}) then
        raise exception '{table} {refusal.replace("'", "''")}' using errcode = '42501';
      end if;"""
        for condition, refusal in checks
    )
    return [
        f"""
    create function public.{function}() returns trigger
    language plpgsql
    set search_path = pg_catalog, pg_temp
    as $$
    begin
{body}
      return new;
    end
    $$
    """,
        f"revoke all on function public.{function}() from public",
        f"""
    create trigger {function}
      before insert or update of {", ".join(columns)} on public.{table}
      for each row execute function public.{function}()
    """,
    ]


# The rows the app may delete (a reading replaces them) and other modules name by id: each id is
# written to drawings_usedid at its row's insert, and refused if it was ever written before, so an id
# once used never names another row, whatever was deleted first, even within one statement.
USED_ID_TABLES = ("drawings_sheet", "drawings_sheetrevision", "drawings_view", "drawings_statesheet")
USED_ID = [
    """
    create function public.drawings_used_id() returns trigger
    language plpgsql
    set search_path = pg_catalog, pg_temp
    as $$
    begin
      if exists (select 1 from public.drawings_usedid u where u.used_id = new.id) then
        raise exception '% names an id used before', tg_table_name using errcode = '42501';
      end if;
      insert into public.drawings_usedid (id, tenant_id, used_id)
        values (uuidv7(), new.tenant_id, new.id);
      return new;
    end
    $$
    """,
    "revoke all on function public.drawings_used_id() from public",
    *(
        f"""
    create trigger drawings_used_id before insert on public.{table}
      for each row execute function public.drawings_used_id()
    """
        for table in USED_ID_TABLES
    ),
]
USED_ID_REVERSE = [
    *(f"drop trigger drawings_used_id on public.{table}" for table in reversed(USED_ID_TABLES)),
    "drop function public.drawings_used_id()",
]

TRIGGERS = [statement for spec in CHECKS for statement in _trigger(*spec)] + USED_ID
TRIGGERS_REVERSE = USED_ID_REVERSE + [
    statement
    for function, table, _columns, _checks in reversed(CHECKS)
    for statement in (
        f"drop trigger {function} on public.{table}",
        f"drop function public.{function}()",
    )
]

FILE_READING_COLUMNS = (
    "revision_id",
    "discipline_id",
    "discipline_source",
    "read_status",
    "read_step",
    "sheets_done",
    "sheets_total",
    "progress_at",
    "sheets_started_at",
    "read_job_id",
    "read_tries",
    "finding",
    "held_answer",
    "cross_check",
    "upload_report",
    "font_report",
    "bangla_ansi",
    "bangla_lines",
    "unmatched_pages",
    "empty_layouts",
    "sheets_refused",
    "cancelled_by",
    "cancelled_by_name",
    "cancelled_by_vextrus",
    "cancelled_at",
)
SHEET_COLUMNS = ("discipline_id", "number", "title", "consultant_office", "storeys_as_stated")
"""What reading a file again, or moving it to another Discipline, may change of a Sheet: never its
set, its Building, its source file or its place."""
PRINTED_SHEET_COLUMNS = (
    "sheet_id",
    "revision_id",
    "location",
    "sheet_key",
    "ordinal",
    "title",
    "revision_mark",
    "issue_date",
    "storeys_as_stated",
    "sources",
    "content_hash",
    "kind",
    "confirmed_kind",
    "source_sha256",
    "reader_version",
    "anchors",
    "proposed_exclusion",
    "proposed_exclusion_text",
    "views_refused",
    "render_file_id",
    "render_key",
    "plot_file_id",
    "plot_page",
    "plot_transform",
    "plot_residual",
    "render_f1",
    "plot_none_reason",
    "decision",
    "confirmation_id",
    "decided_by",
    "decided_at",
    "excluded_reason",
    "excluded_text",
)
"""What a reading, a Plot or a decision may change of a printed sheet: never its set, its source
file or its place."""
VIEW_COLUMNS = (
    "confirmed_kind",
    "decision",
    "confirmation_id",
    "decided_by",
    "decided_at",
    "excluded_reason",
    "excluded_text",
)
"""What a decision may change of a view (a reading replaces views; it never moves one)."""
RIGHTS = [
    f"revoke insert, update, delete on drawings_discipline from {APP}",
    f"revoke update, delete on drawings_readstep from {APP}",
    f"revoke update, delete on drawings_artefact from {APP}",
    f"revoke update, delete on drawings_drawingfile from {APP}",
    f"grant update ({', '.join(FILE_READING_COLUMNS)}) on drawings_drawingfile to {APP}",
    f"revoke update, delete on drawings_drawingset from {APP}",
    f"grant update (name, current_state_id) on drawings_drawingset to {APP}",
    f"revoke update, delete on drawings_drawingsetstate from {APP}",
    f"grant update (status, reader, reader_version) on drawings_drawingsetstate to {APP}",
    f"revoke update, delete on drawings_revision from {APP}",
    f"revoke update on drawings_sheet from {APP}",
    f"grant update ({', '.join(SHEET_COLUMNS)}) on drawings_sheet to {APP}",
    f"revoke update on drawings_sheetrevision from {APP}",
    f"grant update ({', '.join(PRINTED_SHEET_COLUMNS)}) on drawings_sheetrevision to {APP}",
    f"revoke update on drawings_view from {APP}",
    f"grant update ({', '.join(VIEW_COLUMNS)}) on drawings_view to {APP}",
    f"revoke update on drawings_statesheet from {APP}",
    f"revoke update, delete on drawings_usedid from {APP}",
]
RIGHTS_REVERSE = [
    f"grant update, delete on drawings_usedid to {APP}",
    f"grant update on drawings_statesheet to {APP}",
    f"revoke update ({', '.join(VIEW_COLUMNS)}) on drawings_view from {APP}",
    f"grant update on drawings_view to {APP}",
    f"revoke update ({', '.join(PRINTED_SHEET_COLUMNS)}) on drawings_sheetrevision from {APP}",
    f"grant update on drawings_sheetrevision to {APP}",
    f"revoke update ({', '.join(SHEET_COLUMNS)}) on drawings_sheet from {APP}",
    f"grant update on drawings_sheet to {APP}",
    f"grant update, delete on drawings_revision to {APP}",
    f"revoke update (status, reader, reader_version) on drawings_drawingsetstate from {APP}",
    f"grant update, delete on drawings_drawingsetstate to {APP}",
    f"revoke update (name, current_state_id) on drawings_drawingset from {APP}",
    f"grant update, delete on drawings_drawingset to {APP}",
    f"revoke update ({', '.join(FILE_READING_COLUMNS)}) on drawings_drawingfile from {APP}",
    f"grant update, delete on drawings_drawingfile to {APP}",
    f"grant update, delete on drawings_artefact to {APP}",
    f"grant update, delete on drawings_readstep to {APP}",
    f"grant insert, update, delete on drawings_discipline to {APP}",
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Its default privileges give vextrus_app its rights on these tables; the triggers read its
        # StoredFiles, and projects' Projects and Buildings.
        ("platform", "0006_stored_file"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingSet',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('project_id', models.UUIDField(editable=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False, help_text="The Market's Library tenant.")),
                ('key', models.CharField(help_text='Permanent: other modules hold it by value.', max_length=40)),
                ('labels', models.JSONField(help_text='Its one name per language: {language: name}.')),
                ('kind', models.CharField(choices=[('structural', 'Structural'), ('architectural', 'Architectural'), ('mep', 'Mep')], max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('prefixes', models.JSONField(blank=True, default=list, help_text='The sheet-number prefixes it is known by, as a drawing writes them: a list.')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'key'), name='drawings_discipline_key'), models.CheckConstraint(condition=models.Q(('key__regex', '^[a-z][a-z0-9_]*$')), name='drawings_discipline_key_shape'), models.CheckConstraint(condition=models.Q(('kind__in', ['structural', 'architectural', 'mep'])), name='drawings_discipline_kind')],
            },
        ),
        migrations.CreateModel(
            name='DrawingFile',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('format', models.CharField(choices=[('dwg', 'Dwg'), ('pdf', 'Pdf')], editable=False, max_length=8)),
                ('original_name', models.CharField(editable=False, max_length=255)),
                ('size', models.PositiveBigIntegerField(editable=False)),
                ('stored_file_id', models.UUIDField(editable=False)),
                ('discipline_source', models.CharField(blank=True, choices=[('file_name', 'File Name'), ('sheet_numbers', 'Sheet Numbers'), ('qs', 'Qs')], default='', max_length=16)),
                ('building_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('read_status', models.CharField(choices=[('queued', 'Queued'), ('reading', 'Reading'), ('read', 'Read'), ('quarantined', 'Quarantined'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refused', 'Refused')], default='queued', max_length=16)),
                ('read_step', models.CharField(blank=True, help_text='The step reading now.', max_length=64)),
                ('sheets_done', models.PositiveIntegerField(default=0)),
                ('sheets_total', models.PositiveIntegerField(blank=True, help_text='Its sheets (a DWG) or pages (a PDF), once known.', null=True)),
                ('progress_at', models.DateTimeField(blank=True, null=True)),
                ('sheets_started_at', models.DateTimeField(blank=True, null=True)),
                ('read_job_id', models.BigIntegerField(blank=True, null=True)),
                ('read_tries', models.PositiveSmallIntegerField(default=0, help_text='The tries its reading took, when it ended without a job to say so.')),
                ('finding', models.JSONField(blank=True, help_text='Why it is held or failed: a message.', null=True)),
                ('held_answer', models.CharField(blank=True, choices=[('read_anyway', 'Read Anyway'), ('await_resaved', 'Await Resaved'), ('sent_to_vextrus', 'Sent To Vextrus')], default='', max_length=16)),
                ('cross_check', models.JSONField(blank=True, null=True)),
                ('upload_report', models.JSONField(blank=True, null=True)),
                ('font_report', models.JSONField(blank=True, null=True)),
                ('bangla_ansi', models.JSONField(blank=True, null=True)),
                ('bangla_lines', models.JSONField(blank=True, default=list)),
                ('unmatched_pages', models.JSONField(blank=True, default=list)),
                ('empty_layouts', models.PositiveIntegerField(default=0)),
                ('sheets_refused', models.PositiveIntegerField(default=0, help_text='Sheets the reading found and did not keep: a text past its column.')),
                ('added_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('added_by_name', models.CharField(blank=True, editable=False, help_text='Their name at the time, as shown.', max_length=200)),
                ('added_by_vextrus', models.BooleanField(default=False, editable=False, help_text='Added by a Vextrus Engineer: shown with (Vextrus).')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cancelled_by', models.UUIDField(blank=True, null=True)),
                ('cancelled_by_name', models.CharField(blank=True, max_length=200)),
                ('cancelled_by_vextrus', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('discipline', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.discipline')),
                ('drawing_set', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingset')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingSetState',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('seq', models.PositiveIntegerField()),
                ('cause', models.CharField(choices=[('revision', 'Revision'), ('reader_upgrade', 'Reader Upgrade')], max_length=16)),
                ('reader', models.CharField(blank=True, max_length=64)),
                ('reader_version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('read', 'Read'), ('current', 'Current'), ('superseded', 'Superseded')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('drawing_set', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingset')),
                ('parent_state', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingsetstate')),
            ],
        ),
        migrations.AddField(
            model_name='drawingset',
            name='current_state',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingsetstate'),
        ),
        migrations.CreateModel(
            name='ReadStep',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('step', models.CharField(max_length=64)),
                ('input_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('file', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingfile')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('seq', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text='As the consultant marks it.', max_length=32)),
                ('kind', models.CharField(choices=[('first_issue', 'First Issue'), ('reissue', 'Reissue')], max_length=16)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.UUIDField(blank=True, null=True)),
                ('discipline', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.discipline')),
                ('drawing_set', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingset')),
            ],
        ),
        migrations.AddField(
            model_name='drawingsetstate',
            name='revision',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.revision'),
        ),
        migrations.AddField(
            model_name='drawingfile',
            name='revision',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.revision'),
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('building_id', models.UUIDField(blank=True, null=True)),
                ('number', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.TextField(blank=True)),
                ('consultant_office', models.CharField(blank=True, help_text='Empty until M1.', max_length=200)),
                ('storeys_as_stated', models.TextField(blank=True)),
                ('location_key', models.TextField(blank=True, default='')),
                ('discipline', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.discipline')),
                ('drawing_set', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingset')),
                ('source_file', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingfile')),
            ],
        ),
        migrations.CreateModel(
            name='SheetRevision',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('location_key', models.TextField()),
                ('location', models.JSONField()),
                ('sheet_key', models.TextField(blank=True, default='')),
                ('ordinal', models.PositiveIntegerField(help_text="Its place among its file's sheets, from 1.")),
                ('title', models.TextField(blank=True)),
                ('revision_mark', models.CharField(blank=True, max_length=64)),
                ('issue_date', models.CharField(blank=True, max_length=64)),
                ('storeys_as_stated', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(blank=True, default='', help_text='Its kind, as read.', max_length=64)),
                ('confirmed_kind', models.CharField(blank=True, default='', max_length=64)),
                ('source_sha256', models.CharField(max_length=64)),
                ('reader_version', models.CharField(max_length=64)),
                ('anchors', models.JSONField(blank=True, default=list)),
                ('proposed_exclusion', models.CharField(blank=True, choices=[('superseded', 'Superseded'), ('duplicate', 'Duplicate'), ('cover_index', 'Cover Index'), ('for_information', 'For Information'), ('by_others', 'By Others'), ('blank', 'Blank'), ('other', 'Other')], default='', max_length=16)),
                ('proposed_exclusion_text', models.TextField(blank=True)),
                ('views_refused', models.PositiveIntegerField(default=0, help_text='Its views the reading found and did not keep: a text past its column.')),
                ('render_file_id', models.UUIDField(blank=True, null=True)),
                ('render_key', models.CharField(blank=True, help_text="Its render's storage key.", max_length=1200)),
                ('plot_page', models.PositiveIntegerField(blank=True, null=True)),
                ('plot_transform', models.JSONField(blank=True, null=True)),
                ('plot_residual', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('render_f1', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('plot_none_reason', models.CharField(blank=True, choices=[('no_pdf', 'No Pdf'), ('no_page', 'No Page'), ('pdf_refused', 'Pdf Refused'), ('no_number', 'No Number')], default='', max_length=16)),
                ('decision', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('excluded', 'Excluded')], default='', max_length=16)),
                ('confirmation_id', models.UUIDField(blank=True, help_text='An upward stamp.', null=True)),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('excluded_reason', models.CharField(blank=True, choices=[('superseded', 'Superseded'), ('duplicate', 'Duplicate'), ('cover_index', 'Cover Index'), ('for_information', 'For Information'), ('by_others', 'By Others'), ('blank', 'Blank'), ('other', 'Other')], default='', max_length=16)),
                ('excluded_text', models.TextField(blank=True)),
                ('drawing_set', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingset')),
                ('plot_file', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingfile')),
                ('revision', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.revision')),
                ('sheet', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.sheet')),
                ('source_file', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingfile')),
            ],
        ),
        migrations.CreateModel(
            name='StateSheet',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('drawing_set', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingset')),
                ('sheet_revision', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.sheetrevision')),
                ('state', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingsetstate')),
            ],
        ),
        migrations.CreateModel(
            name='UsedId',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('used_id', models.UUIDField(editable=False, help_text='The id a row has had.')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'used_id'), name='drawings_usedid_once')],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('reader_version', models.CharField(max_length=64)),
                ('ordinal', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('plan', 'Plan'), ('section', 'Section'), ('elevation', 'Elevation'), ('schedule', 'Schedule'), ('detail', 'Detail'), ('notes', 'Notes'), ('legend', 'Legend'), ('title_block', 'Title Block'), ('key_plan', 'Key Plan'), ('perspective', 'Perspective')], max_length=16)),
                ('confirmed_kind', models.CharField(blank=True, choices=[('plan', 'Plan'), ('section', 'Section'), ('elevation', 'Elevation'), ('schedule', 'Schedule'), ('detail', 'Detail'), ('notes', 'Notes'), ('legend', 'Legend'), ('title_block', 'Title Block'), ('key_plan', 'Key Plan'), ('perspective', 'Perspective')], default='', max_length=16)),
                ('title', models.TextField(blank=True)),
                ('box', models.JSONField(help_text='[x0, y0, x1, y1] in drawing units, as decimal strings.')),
                ('drawing_unit', models.CharField(blank=True, max_length=8)),
                ('not_to_scale', models.BooleanField(default=False)),
                ('stated_scale_text', models.CharField(blank=True, max_length=64)),
                ('confirmed_scale', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('storeys_as_stated', models.TextField(blank=True)),
                ('storeys', models.JSONField(blank=True, default=list)),
                ('storeys_meaning', models.CharField(blank=True, default='', max_length=16)),
                ('subject', models.CharField(blank=True, default='', max_length=64)),
                ('layer', models.CharField(blank=True, default='', max_length=8)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('proposed_exclusion', models.CharField(blank=True, choices=[('superseded', 'Superseded'), ('duplicate', 'Duplicate'), ('cover_index', 'Cover Index'), ('for_information', 'For Information'), ('by_others', 'By Others'), ('blank', 'Blank'), ('other', 'Other')], default='', max_length=16)),
                ('proposed_exclusion_text', models.TextField(blank=True)),
                ('source_sha256', models.CharField(max_length=64)),
                ('anchors', models.JSONField(blank=True, default=list)),
                ('decision', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('excluded', 'Excluded')], default='', max_length=16)),
                ('confirmation_id', models.UUIDField(blank=True, help_text='An upward stamp.', null=True)),
                ('decided_by', models.UUIDField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('excluded_reason', models.CharField(blank=True, choices=[('superseded', 'Superseded'), ('duplicate', 'Duplicate'), ('cover_index', 'Cover Index'), ('for_information', 'For Information'), ('by_others', 'By Others'), ('blank', 'Blank'), ('other', 'Other')], default='', max_length=16)),
                ('excluded_text', models.TextField(blank=True)),
                ('part', models.ForeignKey(blank=True, db_index=False, help_text='The Discipline Part it is proposed to (an MEP view, or a legend).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.discipline')),
                ('predecessor_view', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.view')),
                ('sheet_revision', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.sheetrevision')),
            ],
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.UUIDField(default=vextrus.platform.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(editable=False)),
                ('reader', models.CharField(max_length=64)),
                ('reader_version', models.CharField(max_length=64)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('insunits', models.PositiveSmallIntegerField(help_text="Its drawing units, as the file's header.")),
                ('stored_file_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('file', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drawings.drawingfile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'file', 'reader', 'reader_version', 'schema_version'), name='drawings_artefact_one_per_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='drawingset',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'project_id'), name='drawings_drawingset_one_per_project'),
        ),
        migrations.AddConstraint(
            model_name='drawingset',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='drawings_drawingset_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='readstep',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'file', 'step', 'input_hash'), name='drawings_readstep_key'),
        ),
        migrations.AddConstraint(
            model_name='readstep',
            constraint=models.CheckConstraint(condition=models.Q(('input_hash__regex', '^[0-9a-f]{64}$')), name='drawings_readstep_hash_hex'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'drawing_set', 'seq'), name='drawings_revision_seq'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'first_issue')), fields=('tenant_id', 'drawing_set', 'discipline'), name='drawings_revision_one_first_issue'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='drawings_revision_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'drawing_set', 'id'), name='drawings_revision_set_id'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['first_issue', 'reissue'])), name='drawings_revision_kind'),
        ),
        migrations.AddConstraint(
            model_name='drawingsetstate',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'drawing_set', 'seq'), name='drawings_drawingsetstate_seq'),
        ),
        migrations.AddConstraint(
            model_name='drawingsetstate',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='drawings_drawingsetstate_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='drawingsetstate',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'drawing_set', 'id'), name='drawings_drawingsetstate_set_id'),
        ),
        migrations.AddConstraint(
            model_name='drawingsetstate',
            constraint=models.CheckConstraint(condition=models.Q(('cause__in', ['revision', 'reader_upgrade'])), name='drawings_drawingsetstate_cause'),
        ),
        migrations.AddConstraint(
            model_name='drawingsetstate',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['reading', 'read', 'current', 'superseded'])), name='drawings_drawingsetstate_status'),
        ),
        migrations.AddConstraint(
            model_name='drawingfile',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'drawing_set', 'sha256'), name='drawings_drawingfile_once'),
        ),
        migrations.AddConstraint(
            model_name='drawingfile',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='drawings_drawingfile_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='drawingfile',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'drawing_set', 'id'), name='drawings_drawingfile_set_id'),
        ),
        migrations.AddConstraint(
            model_name='drawingfile',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='drawings_drawingfile_sha256_hex'),
        ),
        migrations.AddConstraint(
            model_name='drawingfile',
            constraint=models.CheckConstraint(condition=models.Q(('format__in', ['dwg', 'pdf'])), name='drawings_drawingfile_format'),
        ),
        migrations.AddConstraint(
            model_name='drawingfile',
            constraint=models.CheckConstraint(condition=models.Q(('read_status__in', ['queued', 'reading', 'read', 'quarantined', 'failed', 'cancelled', 'refused'])), name='drawings_drawingfile_read_status'),
        ),
        migrations.AddConstraint(
            model_name='drawingfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discipline__isnull', True), ('discipline_source', '')), models.Q(('discipline__isnull', False), ('discipline_source__in', ['file_name', 'sheet_numbers', 'qs'])), _connector='OR'), name='drawings_drawingfile_discipline_source'),
        ),
        migrations.AddConstraint(
            model_name='drawingfile',
            constraint=models.CheckConstraint(condition=models.Q(('original_name', ''), _negated=True), name='drawings_drawingfile_named'),
        ),
        migrations.AddConstraint(
            model_name='drawingfile',
            constraint=models.CheckConstraint(condition=models.Q(('held_answer', ''), models.Q(('held_answer__in', ['read_anyway', 'await_resaved', 'sent_to_vextrus']), ('read_status', 'quarantined')), _connector='OR'), name='drawings_drawingfile_held_answer'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('tenant_id', 'drawing_set', 'building_id', 'discipline', 'number'), name='drawings_sheet_identity', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(condition=models.Q(('number', '')), fields=('tenant_id', 'drawing_set', 'source_file', 'location_key'), name='drawings_sheet_unnumbered_identity'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='drawings_sheet_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'drawing_set', 'id'), name='drawings_sheet_set_id'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('number', ''), _negated=True), ('location_key', ''), ('source_file__isnull', True)), models.Q(('number', ''), ('source_file__isnull', False), models.Q(('location_key', ''), _negated=True)), _connector='OR'), name='drawings_sheet_number_or_place'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'sheet', 'source_file', 'location_key'), name='drawings_sheetrevision_identity'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'source_file', 'location_key'), name='drawings_sheetrevision_one_per_place'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='drawings_sheetrevision_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'drawing_set', 'id'), name='drawings_sheetrevision_set_id'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('source_sha256__regex', '^[0-9a-f]{64}$')), name='drawings_sheetrevision_sha256_hex'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('kind', ''), ('kind__regex', '^[a-z][a-z0-9_]*$'), _connector='OR'), name='drawings_sheetrevision_kind_key'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_kind', ''), ('confirmed_kind__regex', '^[a-z][a-z0-9_]*$'), _connector='OR'), name='drawings_sheetrevision_confirmed_kind_key'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('plot_page__isnull', True), models.Q(('plot_file__isnull', False), ('plot_none_reason', ''), ('plot_page__gte', 1)), _connector='OR'), name='drawings_sheetrevision_plot'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('plot_none_reason', ''), ('plot_none_reason__in', ['no_pdf', 'no_page', 'pdf_refused', 'no_number']), _connector='OR'), name='drawings_sheetrevision_plot_none'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmation_id__isnull', True), ('decision', '')), models.Q(('confirmation_id__isnull', False), ('decision__in', ['confirmed', 'excluded'])), _connector='OR'), name='drawings_sheetrevision_decision_stamped'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'excluded'), ('excluded_reason__in', ['superseded', 'duplicate', 'cover_index', 'for_information', 'by_others', 'blank', 'other'])), models.Q(('decision', ''), ('excluded_reason', '')), models.Q(('decision', 'confirmed'), ('excluded_reason', '')), _connector='OR'), name='drawings_sheetrevision_excluded_reason'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('excluded_reason', 'other'), ('excluded_text__gt', '')), models.Q(('excluded_reason__in', ['superseded', 'duplicate', 'cover_index', 'for_information', 'by_others', 'blank']), ('excluded_text', '')), models.Q(('excluded_reason', ''), ('excluded_text', '')), _connector='OR'), name='drawings_sheetrevision_excluded_text'),
        ),
        migrations.AddConstraint(
            model_name='sheetrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('proposed_exclusion', 'other'), ('proposed_exclusion_text__gt', '')), models.Q(('proposed_exclusion__in', ['superseded', 'duplicate', 'cover_index', 'for_information', 'by_others', 'blank']), ('proposed_exclusion_text', '')), models.Q(('proposed_exclusion', ''), ('proposed_exclusion_text', '')), _connector='OR'), name='drawings_sheetrevision_proposed_exclusion'),
        ),
        migrations.AddConstraint(
            model_name='statesheet',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'state', 'sheet_revision'), name='drawings_statesheet_once'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'sheet_revision', 'reader_version', 'ordinal'), name='drawings_view_identity'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'id'), name='drawings_view_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['plan', 'section', 'elevation', 'schedule', 'detail', 'notes', 'legend', 'title_block', 'key_plan', 'perspective'])), name='drawings_view_kind'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_kind', ''), ('confirmed_kind__in', ['plan', 'section', 'elevation', 'schedule', 'detail', 'notes', 'legend', 'title_block', 'key_plan', 'perspective']), _connector='OR'), name='drawings_view_confirmed_kind'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.CheckConstraint(condition=models.Q(('source_sha256__regex', '^[0-9a-f]{64}$')), name='drawings_view_sha256_hex'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmation_id__isnull', True), ('decision', '')), models.Q(('confirmation_id__isnull', False), ('decision__in', ['confirmed', 'excluded'])), _connector='OR'), name='drawings_view_decision_stamped'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'excluded'), ('excluded_reason__in', ['superseded', 'duplicate', 'cover_index', 'for_information', 'by_others', 'blank', 'other'])), models.Q(('decision', ''), ('excluded_reason', '')), models.Q(('decision', 'confirmed'), ('excluded_reason', '')), _connector='OR'), name='drawings_view_excluded_reason'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('excluded_reason', 'other'), ('excluded_text__gt', '')), models.Q(('excluded_reason__in', ['superseded', 'duplicate', 'cover_index', 'for_information', 'by_others', 'blank']), ('excluded_text', '')), models.Q(('excluded_reason', ''), ('excluded_text', '')), _connector='OR'), name='drawings_view_excluded_text'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('proposed_exclusion', 'other'), ('proposed_exclusion_text__gt', '')), models.Q(('proposed_exclusion__in', ['superseded', 'duplicate', 'cover_index', 'for_information', 'by_others', 'blank']), ('proposed_exclusion_text', '')), models.Q(('proposed_exclusion', ''), ('proposed_exclusion_text', '')), _connector='OR'), name='drawings_view_proposed_exclusion'),
        ),
        migrations.RunSQL(POLICIES, POLICIES_REVERSE),
        migrations.RunSQL(KEYS, KEYS_REVERSE),
        migrations.RunSQL(TRIGGERS, TRIGGERS_REVERSE),
        migrations.RunSQL(RIGHTS, RIGHTS_REVERSE),
    ]
