# Generated by Django 6.1.1 on 2026-09-29 16:14; the grant below is written by hand (ticket nrif), run
# as the owner.
#
# A file's `limit_lines` (every limit that cut its reading) is written by the read job, as vextrus_app,
# like the rest of 0001's FILE_READING_COLUMNS: vextrus_app may update that column and no other new one.

from django.conf import settings
from django.db import migrations, models

APP = settings.VEXTRUS_APP_ROLE


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawingfile",
            name="limit_lines",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Every limit that cut its reading, each once, in the job's order: messages.",
            ),
        ),
        migrations.AlterField(
            model_name="drawingfile",
            name="finding",
            field=models.JSONField(
                blank=True,
                help_text="Why it is held or failed, or the first limit that cut its reading: a message.",
                null=True,
            ),
        ),
        migrations.RunSQL(
            f"grant update (limit_lines) on drawings_drawingfile to {APP}",
            f"revoke update (limit_lines) on drawings_drawingfile from {APP}",
        ),
    ]
