# A file that could not be read, marked for Vextrus to look at (ticket 21c; m0-screens 4.5's Failed
# row, "Mark for Vextrus"). Generated by Django 6.1.1 on 2026-09-29, then vextrus_app's right written
# by hand. Run as the owner.
#
# 0001 revoked UPDATE on drawings_drawingfile and granted it back column by column (its
# FILE_READING_COLUMNS), so a new column is not the app's to change until it is granted here, the
# same way.

from django.conf import settings
from django.db import migrations, models

APP = settings.VEXTRUS_APP_ROLE


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawingfile",
            name="marked_for_vextrus",
            field=models.BooleanField(
                default=False,
                help_text="A file that could not be read, marked for Vextrus to look at.",
            ),
        ),
        migrations.RunSQL(
            [f"grant update (marked_for_vextrus) on drawings_drawingfile to {APP}"],
            [f"revoke update (marked_for_vextrus) on drawings_drawingfile from {APP}"],
        ),
    ]
