"""Write `src/modules/takeoff/viewer/drawn-advance.ts`: the advance a drawing's text is lettered at.

The face is DejaVu Sans (Bitstream Vera's metrics), the face ezdxf's drawing add-on -- the product's
DWG lane picture, `drawing_render` -- letters a drawing's text in where the style's own font is not
installed, set so that the capital A stands the text's height, with no kerning (Decision
I-648). The figures are read through ezdxf's own renderer of that file and one run is checked
against ezdxf's `get_text_length`, so the table is the lane's arithmetic and nothing else.

    uv run --project cad python tests/takeoff/viewer/support/drawn-advance.gen.py
"""

from __future__ import annotations

import json
from pathlib import Path

from ezdxf.fonts import fonts
from ezdxf.fonts.ttfonts import TTFontRenderer

OUT = Path(__file__).resolve().parents[4] / "src/modules/takeoff/viewer/drawn-advance.ts"
FACE = "DejaVuSans.ttf"

#: The characters the table states: printable ASCII, Latin-1, Greek, and the signs the atlas holds.
SIGNS = "Ø°±×²³·−→≤≥√Σµφ½¼¾⌀∅⌊⌋⌈⌉�"
CHARACTERS = list(
    dict.fromkeys(
        [chr(c) for c in range(0x20, 0x7F)]
        + [chr(c) for c in range(0xA0, 0x100)]
        + [chr(c) for c in range(0x391, 0x3CA) if c != 0x3A2]
        + list(SIGNS)
    )
)


def main() -> None:
    tt = fonts.font_manager.get_ttf_font(FACE)
    lane = TTFontRenderer(tt)
    cmap = tt.getBestCmap()
    hmtx = tt["hmtx"]
    cap = lane.font_measurements.cap_height
    assert cap == int(cap), cap
    missing = hmtx[".notdef"][0]
    units = {ch: hmtx[cmap[ord(ch)]][0] if ord(ch) in cmap else missing for ch in CHARACTERS}
    probe = '2" clear cover (pile caps)'
    ours = sum(units[c] for c in probe) / cap
    theirs = lane.get_text_length(probe, 1.0)
    assert abs(ours - theirs) < 1e-9, (ours, theirs)
    version = tt["name"].getDebugName(5)
    body = "\n".join(f"  {json.dumps(ch, ensure_ascii=False)}: {units[ch]}," for ch in CHARACTERS)
    OUT.write_text(
        "// Generated by tests/takeoff/viewer/support/drawn-advance.gen.py; regenerate rather than edit.\n"
        f"// DejaVu Sans {version}: the advance a drawing's text is lettered at (Decision I-648).\n\n"
        "/** The face's units a capital A stands (the cap height a record's height is), and the advance of a character it has no glyph for (.notdef). */\n"
        f"export const DRAWN_UNITS = Object.freeze({{ cap: {int(cap)}, missing: {missing} }});\n\n"
        "/** Each character's advance, in the face's units. */\n"
        f"export const DRAWN_ADVANCE_UNITS: Readonly<Record<string, number>> = Object.freeze({{\n{body}\n}});\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.name}: {len(units)} characters, cap {int(cap)}, probe {ours:.6f} cap heights")


if __name__ == "__main__":
    main()
