# Generated by Django 6.1.1 on 2026-09-29, then row-level security, the same-Project keys, the reach
# trigger and vextrus_app's rights written by hand (ticket 19a; docs/data-model.md §2 and §3.4). Run as
# the owner.
#
# - Every takeoff table has row-level security ENABLED, never forced, and its own-tenant policy for
#   reads and writes alike. `takeoff_takeoffstep` and `takeoff_check` are Library tables: each adds one
#   FOR SELECT policy admitting the acting tenant's Market Library through app.library_id, and
#   vextrus_app may only SELECT them (sync_library writes them as the owner). No policy holds a join,
#   a sub-select or any other function call.
# - A reference inside takeoff names a row of the same tenant and the same Project: a composite key on
#   (tenant_id, project_id, x_id) beside Django's own, deferred, so no write crosses Projects inside
#   one Developer.
# - What a key cannot hold, a trigger does, whoever writes, on INSERT and on UPDATE: a row's Project is
#   one the writer can read (projects' own-tenant policy), and its Building, when it names one, is a
#   Building of that Project. The function runs as its caller (not SECURITY DEFINER); the owner sees
#   every row and passes.
# - vextrus_app's rights come from platform's default privileges (platform 0003): select, insert,
#   update and delete, never TRUNCATE. Then narrowed: nothing of takeoff's is ever deleted by the app
#   (an act is undone by stamping, never by deleting); a Confirmation is never changed but for its
#   `undone_at`; a drawing list, its entries, a Trace, a Question's link, a Check's run and its
#   findings are only ever added; a row never moves to another tenant, Project or Building.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import vextrus.platform.ids

APP = settings.VEXTRUS_APP_ROLE

OWN_TENANT = "tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid"
LIBRARY = "tenant_id = nullif(current_setting('app.library_id', true), '')::uuid"

LIBRARY_TABLES = ("takeoff_takeoffstep", "takeoff_check")
TENANT_TABLES = (
    "takeoff_stepprogress",
    "takeoff_recogniserun",
    "takeoff_proposal",
    "takeoff_proposaltrace",
    "takeoff_confirmation",
    "takeoff_question",
    "takeoff_questionlink",
    "takeoff_checkrun",
    "takeoff_checkfinding",
    "takeoff_coverage",
    "takeoff_coveragestep",
    "takeoff_drawingregister",
    "takeoff_registerentry",
)
TABLES = LIBRARY_TABLES + TENANT_TABLES
WITH_BUILDING = (
    "takeoff_stepprogress",
    "takeoff_recogniserun",
    "takeoff_confirmation",
    "takeoff_question",
)

POLICIES = [
    *(f"alter table {table} enable row level security" for table in TABLES),
    *(f"create policy own_tenant on {table} using ({OWN_TENANT})" for table in TABLES),
    *(
        f"create policy library_reads on {table} for select using ({LIBRARY})"
        for table in LIBRARY_TABLES
    ),
]
POLICIES_REVERSE = [
    *(f"drop policy library_reads on {table}" for table in LIBRARY_TABLES),
    *(f"drop policy own_tenant on {table}" for table in TABLES),
    *(f"alter table {table} disable row level security" for table in TABLES),
]

# (table, column, the table it names): each reference held inside its row's tenant and Project.
REFERENCES = (
    ("takeoff_proposal", "run_id", "takeoff_recogniserun"),
    ("takeoff_proposal", "supersedes_id", "takeoff_proposal"),
    ("takeoff_proposal", "confirmation_id", "takeoff_confirmation"),
    ("takeoff_proposaltrace", "proposal_id", "takeoff_proposal"),
    ("takeoff_proposaltrace", "question_id", "takeoff_question"),
    ("takeoff_confirmation", "question_id", "takeoff_question"),
    ("takeoff_questionlink", "question_id", "takeoff_question"),
    ("takeoff_questionlink", "proposal_id", "takeoff_proposal"),
    ("takeoff_checkrun", "confirmation_id", "takeoff_confirmation"),
    ("takeoff_checkfinding", "run_id", "takeoff_checkrun"),
    ("takeoff_checkfinding", "question_id", "takeoff_question"),
    ("takeoff_coverage", "confirmation_id", "takeoff_confirmation"),
    ("takeoff_coveragestep", "coverage_id", "takeoff_coverage"),
    ("takeoff_drawingregister", "confirmation_id", "takeoff_confirmation"),
    ("takeoff_registerentry", "register_id", "takeoff_drawingregister"),
)


def _key_name(table, column):
    return f"{table}_{column}_same_project"[:63]


KEYS = [
    f"""alter table {table} add constraint {_key_name(table, column)}
          foreign key (tenant_id, project_id, {column}) references {target} (tenant_id, project_id, id)
          deferrable initially deferred"""
    for table, column, target in REFERENCES
]
KEYS_REVERSE = [
    f"alter table {table} drop constraint {_key_name(table, column)}"
    for table, column, _target in reversed(REFERENCES)
]

TRIGGERS = [
    """
    create function public.takeoff_in_reach() returns trigger
    language plpgsql
    set search_path = pg_catalog, pg_temp
    as $$
    begin
      if tg_op = 'UPDATE' and (new.tenant_id <> old.tenant_id or new.project_id <> old.project_id) then
        raise exception '% rows never move to another Project', tg_table_name
          using errcode = '42501';
      end if;
      if not exists (select 1 from public.projects_project where id = new.project_id) then
        raise exception '% names a Project the writer cannot read', tg_table_name
          using errcode = '42501';
      end if;
      -- Only the tables with a Building pass 'building': plpgsql resolves new.building_id when the
      -- statement runs, so it is read inside this branch only.
      if tg_argv[0] = 'building' then
        if tg_op = 'UPDATE' then
          if new.building_id is distinct from old.building_id then
            raise exception '% rows never move to another Building', tg_table_name
              using errcode = '42501';
          end if;
        end if;
        if new.building_id is not null then
          if not exists (
            select 1 from public.projects_building
             where id = new.building_id and project_id = new.project_id
          ) then
            raise exception '% names a Building not of its Project', tg_table_name
              using errcode = '42501';
          end if;
        end if;
      end if;
      return new;
    end
    $$
    """,
    "revoke all on function public.takeoff_in_reach() from public",
    f"grant execute on function public.takeoff_in_reach() to {APP}",
    *(
        f"""create trigger takeoff_in_reach before insert or update on {table}
            for each row execute function public.takeoff_in_reach('{
            "building" if table in WITH_BUILDING else "project"}')"""
        for table in TENANT_TABLES
    ),
]
TRIGGERS_REVERSE = [
    *(f"drop trigger takeoff_in_reach on {table}" for table in TENANT_TABLES),
    "drop function public.takeoff_in_reach()",
]

APPEND_ONLY = (
    "takeoff_drawingregister",
    "takeoff_registerentry",
    "takeoff_proposaltrace",
    "takeoff_questionlink",
    "takeoff_checkrun",
    "takeoff_checkfinding",
)
RIGHTS = [
    *(f"revoke insert, update, delete on {table} from {APP}" for table in LIBRARY_TABLES),
    *(f"revoke delete on {table} from {APP}" for table in TENANT_TABLES),
    *(f"revoke update on {table} from {APP}" for table in APPEND_ONLY),
    f"revoke update on takeoff_confirmation from {APP}",
    f"grant update (undone_at) on takeoff_confirmation to {APP}",
]
RIGHTS_REVERSE = [
    f"revoke update (undone_at) on takeoff_confirmation from {APP}",
    f"grant update on takeoff_confirmation to {APP}",
    *(f"grant update on {table} to {APP}" for table in APPEND_ONLY),
    *(f"grant delete on {table} to {APP}" for table in TENANT_TABLES),
    *(f"grant insert, update, delete on {table} to {APP}" for table in LIBRARY_TABLES),
]


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Its default privileges give vextrus_app its rights on these tables; the trigger reads
        # projects' Projects and Buildings.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("platform", "0008_jev"),
        ("projects", "0003_a_building_keeps_its_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        editable=False, help_text="The Market's Library tenant."
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The Check's code: permanent.", max_length=64
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("family_key", models.CharField(blank=True, default="", max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("source", "Source"),
                            ("conservation", "Conservation"),
                            ("sanity", "Sanity"),
                            ("relation", "Relation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message_code", models.CharField(max_length=128)),
                ("milestone", models.CharField(max_length=8)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "key", "version"),
                        name="takeoff_check_key_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("key__regex", "^[a-z][a-z0-9_]*$")),
                        name="takeoff_check_key_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                ["source", "conservation", "sanity", "relation"],
                            )
                        ),
                        name="takeoff_check_kind",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Confirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                ("step", models.CharField(max_length=40)),
                (
                    "building_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("discipline", models.CharField(blank=True, default="", max_length=40)),
                (
                    "by_name",
                    models.CharField(
                        help_text="Who, by their name as it was then.", max_length=200
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bulk", "Bulk"),
                            ("single", "Single"),
                            ("question_answer", "Question Answer"),
                            ("step_close", "Step Close"),
                            ("revision", "Revision"),
                            ("unconfirm", "Unconfirm"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "act",
                    models.CharField(
                        choices=[
                            ("confirm", "Confirm"),
                            ("exclude", "Exclude"),
                            ("drawing_list", "Drawing List"),
                        ],
                        max_length=16,
                    ),
                ),
                ("proposals", models.PositiveIntegerField(default=0)),
                (
                    "model_version_seq",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "before",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="What it overwrote, by printed sheet: {sheets: {id: {decision, confirmation_id, kind, reason, text}}}; undo puts back the newest of those still standing.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                ("check_key", models.CharField(max_length=64)),
                ("check_version", models.PositiveIntegerField()),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("read", "Read"),
                            ("confirmation", "Confirmation"),
                            ("boq", "Boq"),
                        ],
                        max_length=16,
                    ),
                ),
                ("passed", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("drawing_set_state_id", models.UUIDField(blank=True, null=True)),
                (
                    "at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "confirmation",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.confirmation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                (
                    "drawing_set_state_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("view_id", models.UUIDField(editable=False)),
                ("sheet_revision_id", models.UUIDField(editable=False)),
                (
                    "proposed_status",
                    models.CharField(
                        choices=[
                            ("unaccounted", "Unaccounted"),
                            ("assigned", "Assigned"),
                            ("used", "Used"),
                            ("excluded", "Excluded"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "proposed_reason",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unaccounted", "Unaccounted"),
                            ("assigned", "Assigned"),
                            ("used", "Used"),
                            ("excluded", "Excluded"),
                        ],
                        max_length=16,
                    ),
                ),
                ("part_key", models.CharField(blank=True, default="", max_length=40)),
                ("reason", models.CharField(blank=True, default="", max_length=24)),
                (
                    "reason_text",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "confirmation",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.confirmation",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoverageStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                ("step", models.CharField(max_length=40)),
                ("used", models.BooleanField(default=False)),
                (
                    "coverage",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.coverage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrawingRegister",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                ("discipline", models.CharField(max_length=40)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("sheet", "Sheet"),
                            ("pasted", "Pasted"),
                            ("typed", "Typed"),
                        ],
                        max_length=8,
                    ),
                ),
                ("source_sheet_id", models.UUIDField(blank=True, null=True)),
                (
                    "entered_by_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "entered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("raw_text", models.TextField(blank=True, default="")),
                ("ignored", models.PositiveIntegerField(default=0)),
                (
                    "confirmation",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.confirmation",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                ("step", models.CharField(max_length=40)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("element", "Element"),
                            ("relation", "Relation"),
                            ("sheet", "Sheet"),
                            ("view", "View"),
                            ("drafting_profile", "Drafting Profile"),
                        ],
                        max_length=24,
                    ),
                ),
                ("subject_id", models.UUIDField(editable=False)),
                ("family_key", models.CharField(blank=True, default="", max_length=64)),
                ("candidate_key", models.CharField(max_length=128)),
                ("outcome", models.CharField(default="first_read", max_length=16)),
                ("values", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(default="reader", max_length=32)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("reader", models.CharField(blank=True, default="", max_length=64)),
                (
                    "reader_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("candidate_geometry", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("blocked", "Blocked"),
                            ("held", "Held"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "rejected_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("jev_answer_id", models.UUIDField(blank=True, null=True)),
                (
                    "jev_pick",
                    models.JSONField(
                        blank=True,
                        help_text="Jev's answer: {choice, options}, its keys in order.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "confirmation",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.confirmation",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.proposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                ("step", models.CharField(max_length=40)),
                (
                    "building_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("discipline", models.CharField(blank=True, default="", max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("missing", "Missing"),
                            ("conflict", "Conflict"),
                            ("low_confidence", "Low Confidence"),
                            ("check", "Check"),
                            ("file_misread", "File Misread"),
                            ("labour_source", "Labour Source"),
                            ("relation", "Relation"),
                            ("missing_discipline", "Missing Discipline"),
                            ("convention", "Convention"),
                        ],
                        max_length=24,
                    ),
                ),
                ("question_key", models.CharField(max_length=64)),
                ("subject_id", models.UUIDField(blank=True, null=True)),
                ("message_code", models.CharField(max_length=128)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("options", models.JSONField(blank=True, default=list)),
                ("check_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("answered", "Answered"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("answer", models.JSONField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProposalTrace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                ("fact", models.CharField(max_length=64)),
                ("anchor", models.JSONField()),
                (
                    "proposal",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.proposal",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.question",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="confirmation",
            name="question",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="takeoff.question",
            ),
        ),
        migrations.CreateModel(
            name="CheckFinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                ("subject_ids", models.JSONField(blank=True, default=list)),
                ("message_code", models.CharField(max_length=128)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.checkrun",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                (
                    "proposal",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.proposal",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecogniseRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                (
                    "building_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "drawing_set_state_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("family_key", models.CharField(max_length=64)),
                (
                    "drafting_profile_version_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("cache_key", models.CharField(max_length=64)),
                ("status", models.CharField(default="done", max_length=16)),
                ("candidates", models.PositiveIntegerField(default=0)),
                ("reused_answers", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant_id",
                            "project_id",
                            "building_id",
                            "family_key",
                            "cache_key",
                        ),
                        name="takeoff_recogniserun_one",
                        nulls_distinct=False,
                    ),
                    models.UniqueConstraint(
                        fields=("tenant_id", "project_id", "id"),
                        name="takeoff_recogniserun_project_id",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="proposal",
            name="run",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="takeoff.recogniserun",
            ),
        ),
        migrations.CreateModel(
            name="RegisterEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                ("number", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                (
                    "revision_mark",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("line", models.PositiveIntegerField()),
                (
                    "register",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="takeoff.drawingregister",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StepProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("project_id", models.UUIDField(editable=False)),
                (
                    "building_id",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                ("step", models.CharField(max_length=40)),
                ("discipline", models.CharField(blank=True, default="", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("reading", "Reading"),
                            ("in_review", "In Review"),
                            ("confirmed", "Confirmed"),
                            ("closed_with_questions", "Closed With Questions"),
                            ("reopened", "Reopened"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                (
                    "placed",
                    models.PositiveIntegerField(
                        default=0, help_text="n: decided so far."
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        blank=True, help_text="N; empty while unknown.", null=True
                    ),
                ),
                ("open_questions", models.PositiveIntegerField(default=0)),
                ("awaiting_answer", models.PositiveIntegerField(default=0)),
                ("active_seconds", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant_id",
                            "project_id",
                            "building_id",
                            "step",
                            "discipline",
                        ),
                        name="takeoff_stepprogress_one",
                        nulls_distinct=False,
                    ),
                    models.UniqueConstraint(
                        fields=("tenant_id", "project_id", "id"),
                        name="takeoff_stepprogress_project_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "not_started",
                                    "reading",
                                    "in_review",
                                    "confirmed",
                                    "closed_with_questions",
                                    "reopened",
                                ],
                            )
                        ),
                        name="takeoff_stepprogress_status",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TakeoffStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        editable=False, help_text="The Market's Library tenant."
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "key",
                    models.CharField(
                        help_text="Permanent: held by value.", max_length=40
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        help_text="Its one name per language: {language: name}."
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        help_text="`building` for steps 1 to 4 and 14, else its Discipline Part's key.",
                        max_length=40,
                    ),
                ),
                ("milestone", models.CharField(max_length=8)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "key"), name="takeoff_takeoffstep_key"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("key__regex", "^[a-z][a-z0-9_]*$")),
                        name="takeoff_takeoffstep_key_shape",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="checkrun",
            index=models.Index(
                fields=["tenant_id", "project_id", "check_key"],
                name="takeoff_checkrun_project_id_ch",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkrun",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_checkrun_project_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("trigger__in", ["read", "confirmation", "boq"])),
                name="takeoff_checkrun_trigger",
            ),
        ),
        migrations.AddIndex(
            model_name="coverage",
            index=models.Index(
                fields=["tenant_id", "project_id", "sheet_revision_id"],
                name="takeoff_coverage_project_id_sh",
            ),
        ),
        migrations.AddConstraint(
            model_name="coverage",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "drawing_set_state_id", "view_id"),
                name="takeoff_coverage_one",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="coverage",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_coverage_project_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="coverage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["unaccounted", "assigned", "used", "excluded"]),
                    (
                        "proposed_status__in",
                        ["unaccounted", "assigned", "used", "excluded"],
                    ),
                ),
                name="takeoff_coverage_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="coverage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "excluded"), _negated=True),
                    models.Q(("reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="takeoff_coverage_excluded_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="coveragestep",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "coverage", "step"),
                name="takeoff_coveragestep_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="coveragestep",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_coveragestep_project_id",
            ),
        ),
        migrations.AddIndex(
            model_name="drawingregister",
            index=models.Index(
                fields=["tenant_id", "project_id", "discipline"],
                name="takeoff_drawingregister_projec",
            ),
        ),
        migrations.AddConstraint(
            model_name="drawingregister",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_drawingregister_project_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="drawingregister",
            constraint=models.CheckConstraint(
                condition=models.Q(("source__in", ["sheet", "pasted", "typed"])),
                name="takeoff_register_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="drawingregister",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "sheet"), ("source_sheet_id__isnull", False)),
                    models.Q(
                        models.Q(("source", "sheet"), _negated=True),
                        ("confirmation__isnull", False),
                        ("entered_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="takeoff_register_whence",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["tenant_id", "project_id", "created_at"],
                name="takeoff_question_project_id_cr",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "question_key"),
                name="takeoff_question_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_question_project_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "missing",
                            "conflict",
                            "low_confidence",
                            "check",
                            "file_misread",
                            "labour_source",
                            "relation",
                            "missing_discipline",
                            "convention",
                        ],
                    )
                ),
                name="takeoff_question_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["open", "answered", "withdrawn"])),
                name="takeoff_question_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "answered"), _negated=True),
                    models.Q(("answer__isnull", False), ("answered_at__isnull", False)),
                    _connector="OR",
                ),
                name="takeoff_question_answered",
            ),
        ),
        migrations.AddIndex(
            model_name="proposaltrace",
            index=models.Index(
                fields=["tenant_id", "proposal"], name="takeoff_proposaltrace_proposal"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposaltrace",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_proposaltrace_project_id",
            ),
        ),
        migrations.AddIndex(
            model_name="confirmation",
            index=models.Index(
                fields=["tenant_id", "project_id", "user", "at"],
                name="takeoff_confirmation_project_i",
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmation",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_confirmation_project_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "bulk",
                            "single",
                            "question_answer",
                            "step_close",
                            "revision",
                            "unconfirm",
                        ],
                    )
                ),
                name="takeoff_confirmation_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmation",
            constraint=models.CheckConstraint(
                condition=models.Q(("act__in", ["confirm", "exclude", "drawing_list"])),
                name="takeoff_confirmation_act",
            ),
        ),
        migrations.AddIndex(
            model_name="checkfinding",
            index=models.Index(
                fields=["tenant_id", "run"], name="takeoff_checkfinding_run"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkfinding",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_checkfinding_project_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionlink",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "question", "proposal"),
                name="takeoff_questionlink_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionlink",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_questionlink_project_id",
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["tenant_id", "project_id", "subject_id"],
                name="takeoff_proposal_project_id_su",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "step", "candidate_key"),
                name="takeoff_proposal_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_proposal_project_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "subject__in",
                        ["element", "relation", "sheet", "view", "drafting_profile"],
                    )
                ),
                name="takeoff_proposal_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "open",
                            "blocked",
                            "held",
                            "confirmed",
                            "rejected",
                            "superseded",
                        ],
                    )
                ),
                name="takeoff_proposal_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("jev_answer_id__isnull", True),
                    ("jev_pick__isnull", False),
                    _connector="OR",
                ),
                name="takeoff_proposal_jev_pick",
            ),
        ),
        migrations.AddConstraint(
            model_name="registerentry",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "register", "number"),
                name="takeoff_registerentry_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="registerentry",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "project_id", "id"),
                name="takeoff_registerentry_project_id",
            ),
        ),
        migrations.RunSQL(POLICIES, POLICIES_REVERSE),
        migrations.RunSQL(KEYS, KEYS_REVERSE),
        migrations.RunSQL(TRIGGERS, TRIGGERS_REVERSE),
        migrations.RunSQL(RIGHTS, RIGHTS_REVERSE),
    ]
