# Generated by Django 6.1.1 on 2026-09-30, then the same-Project key written by hand (#158; as 0001's).
# Run as the owner.
#
# - `assign`, the QS's act putting a view in Takeoff Steps, joins the acts a Confirmation may be.
# - A CoverageStep names the act that gave it (none: the read proposed it). Like every reference inside
#   takeoff it names a Confirmation of the same tenant and Project: a composite key beside Django's own,
#   deferred. The app's rights are 0001's: it may add and change a CoverageStep, never delete one, so
#   an undone act's steps stay, standing no more. Each act that gives a view a step keeps a row of
#   its own (one per view, step and act; the read's, with no act, once), so undoing one act never
#   takes back a step another act still standing gave.

import django.db.models.deletion
from django.db import migrations, models

KEY = "takeoff_coveragestep_confirmation_id_same_project"

KEYS = [
    f"""alter table takeoff_coveragestep add constraint {KEY}
          foreign key (tenant_id, project_id, confirmation_id)
          references takeoff_confirmation (tenant_id, project_id, id)
          deferrable initially deferred"""
]
KEYS_REVERSE = [f"alter table takeoff_coveragestep drop constraint {KEY}"]


class Migration(migrations.Migration):
    dependencies = [
        ("takeoff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="confirmation",
            name="takeoff_confirmation_act",
        ),
        migrations.AddField(
            model_name="coveragestep",
            name="confirmation",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="takeoff.confirmation",
            ),
        ),
        migrations.AlterField(
            model_name="confirmation",
            name="act",
            field=models.CharField(
                choices=[
                    ("confirm", "Confirm"),
                    ("exclude", "Exclude"),
                    ("drawing_list", "Drawing List"),
                    ("assign", "Assign"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmation",
            constraint=models.CheckConstraint(
                condition=models.Q(("act__in", ["confirm", "exclude", "drawing_list", "assign"])),
                name="takeoff_confirmation_act",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="coveragestep",
            name="takeoff_coveragestep_one",
        ),
        migrations.AddConstraint(
            model_name="coveragestep",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "coverage", "step", "confirmation"),
                name="takeoff_coveragestep_one",
                nulls_distinct=False,
            ),
        ),
        migrations.RunSQL(KEYS, KEYS_REVERSE),
    ]
