# Generated by Django 6.1.1 on 2026-09-30, then the same-Project key written by hand (ticket 21c,
# review round 4): the exclusion that withdrew a Question, in its own column so no answer overwrites
# it. Like every reference inside takeoff (0001), it names a Confirmation of the row's own tenant and
# Project. Run as the owner.

import django.db.models.deletion
from django.db import migrations, models

KEY = "takeoff_question_withdrawn_by_id_same_project"


class Migration(migrations.Migration):

    dependencies = [
        ("takeoff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="withdrawn_by",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                help_text="The exclusion that withdrew it (its sheet left out); no answer overwrites it, and the exclusion's undo asks it again.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="takeoff.confirmation",
            ),
        ),
        migrations.RunSQL(
            f"""alter table takeoff_question add constraint {KEY}
                  foreign key (tenant_id, project_id, withdrawn_by_id)
                  references takeoff_confirmation (tenant_id, project_id, id)
                  deferrable initially deferred""",
            f"alter table takeoff_question drop constraint {KEY}",
        ),
    ]
