# Generated by Django 6.1.1 on 2026-10-07 12:30 (ticket S16-T2; M1.md C9). Run as the owner.
#
# A Confirmation's act widens from 16 to 32 characters (C9: `close_with_questions` is 20) and gains
# `edit` (values the QS typed, Step 6's size answer) and `unconfirm` (confirmed Elements made
# Proposals again). The app's rights are 0001's: it inserts Confirmations and changes only undone_at.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("takeoff", "0003_assign_act"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="confirmation",
            name="takeoff_confirmation_act",
        ),
        migrations.AlterField(
            model_name="confirmation",
            name="act",
            field=models.CharField(
                choices=[
                    ("confirm", "Confirm"),
                    ("exclude", "Exclude"),
                    ("drawing_list", "Drawing List"),
                    ("assign", "Assign"),
                    ("edit", "Edit"),
                    ("unconfirm", "Unconfirm"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "act__in",
                        [
                            "confirm",
                            "exclude",
                            "drawing_list",
                            "assign",
                            "edit",
                            "unconfirm",
                        ],
                    )
                ),
                name="takeoff_confirmation_act",
            ),
        ),
    ]
