# Generated by Django 6.1.1 on 2026-10-07, then row-level security, the same-tenant key and
# vextrus_app's rights written by hand (ticket S16-RT; docs/data-model.md §2 and §3.4). Run as the owner.
#
# - Every rates table has row-level security ENABLED, never forced, and its own-tenant policy for
#   reads and writes alike, plus one FOR SELECT policy admitting the acting tenant's Market Library
#   through app.library_id. No policy holds a join, a sub-select or any other function call.
# - The Resources, the Rate Analyses and their lines are the Library's alone: vextrus_app may only
#   SELECT them (sync_library writes them as the owner).
# - A Market Price names a set of its own tenant (a composite key beside Django's own, deferred); it
#   names a Resource of the Library, which is another tenant's, so that key is Django's alone.
# - A Developer's set and its prices are written by the app (the copy, then each edit); nothing of
#   rates' is ever deleted by the app, and a row never moves to another tenant.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import vextrus.platform.ids

APP = settings.VEXTRUS_APP_ROLE

OWN_TENANT = "tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid"
LIBRARY = "tenant_id = nullif(current_setting('app.library_id', true), '')::uuid"

LIBRARY_ONLY = ("rates_resource", "rates_rateanalysis", "rates_rateanalysisline")
TENANT_WRITTEN = ("rates_marketpriceset", "rates_marketprice")
TABLES = LIBRARY_ONLY + TENANT_WRITTEN

POLICIES = [
    *(f"alter table {table} enable row level security" for table in TABLES),
    *(f"create policy own_tenant on {table} using ({OWN_TENANT})" for table in TABLES),
    *(f"create policy library_reads on {table} for select using ({LIBRARY})" for table in TABLES),
]
POLICIES_REVERSE = [
    *(f"drop policy library_reads on {table}" for table in TABLES),
    *(f"drop policy own_tenant on {table}" for table in TABLES),
    *(f"alter table {table} disable row level security" for table in TABLES),
]

KEYS = [
    """alter table rates_marketprice add constraint rates_marketprice_same_tenant_set
         foreign key (tenant_id, price_set_id) references rates_marketpriceset (tenant_id, id)
         deferrable initially deferred""",
]
KEYS_REVERSE = ["alter table rates_marketprice drop constraint rates_marketprice_same_tenant_set"]

RIGHTS = [
    *(f"revoke insert, update, delete on {table} from {APP}" for table in LIBRARY_ONLY),
    *(f"revoke delete on {table} from {APP}" for table in TENANT_WRITTEN),
]
RIGHTS_REVERSE = [
    *(f"grant delete on {table} to {APP}" for table in TENANT_WRITTEN),
    *(f"grant insert, update, delete on {table} to {APP}" for table in LIBRARY_ONLY),
]


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # Its default privileges give vextrus_app its rights on these tables.
        ("platform", "0008_jev"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPriceSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                ("effective_date", models.DateField()),
                ("label", models.CharField(max_length=200)),
                (
                    "currency",
                    models.CharField(
                        help_text="The Market's currency, as its row gives it.",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("frozen", "Frozen")],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=300)),
                (
                    "parent_set",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rates.marketpriceset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RateAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(editable=False, help_text="The Market's Library tenant."),
                ),
                ("item_code", models.CharField(max_length=64)),
                ("per_unit", models.CharField(max_length=16)),
                ("shown_per", models.PositiveSmallIntegerField(default=100)),
                ("mix", models.CharField(blank=True, default="", max_length=16)),
                (
                    "dry_volume_factor",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
                ),
                (
                    "benchmark_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The Market's benchmark item, e.g. `07.3.2`.",
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "item_code"),
                        name="rates_rateanalysis_item",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(editable=False, help_text="The Market's Library tenant."),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Permanent, lower-case words: `cement_opc`.",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("labour", "Labour"),
                            ("plant", "Plant"),
                            ("labour_contract", "Labour Contract"),
                            ("material_and_labour", "Material And Labour"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "quoted_unit",
                    models.CharField(help_text="A plain code: bag, cft, kg, sft, nos.", max_length=16),
                ),
                (
                    "schedule_group",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("in_material_schedule", models.BooleanField(default=False)),
                (
                    "procurement_lead_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ordinal",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Where the Resource sits in the list of prices.",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("tenant_id", "code"), name="rates_resource_code")
                ],
            },
        ),
        migrations.CreateModel(
            name="RateAnalysisLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(editable=False, help_text="The Market's Library tenant."),
                ),
                ("kind", models.CharField(max_length=16)),
                ("ordinal", models.PositiveSmallIntegerField()),
                ("qty_per_unit", models.DecimalField(decimal_places=6, max_digits=14)),
                (
                    "wastage_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="rates.rateanalysis",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rates.resource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=vextrus.platform.ids.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(editable=False)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Empty: the rate is not entered.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by_user_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Who last changed it; empty for the starter's own value.",
                        null=True,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "price_set",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="rates.marketpriceset",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rates.resource",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="marketpriceset",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "effective_date", "label"),
                name="rates_marketpriceset_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketpriceset",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "id"), name="rates_marketpriceset_tenant_id"
            ),
        ),
        migrations.AddIndex(
            model_name="rateanalysisline",
            index=models.Index(fields=["tenant_id", "analysis"], name="rates_line_tenant_analysis"),
        ),
        migrations.AddConstraint(
            model_name="rateanalysisline",
            constraint=models.UniqueConstraint(
                fields=("analysis", "ordinal"), name="rates_rateanalysisline_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="rateanalysisline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_per_unit__gt", 0), ("wastage_pct__gte", 0)),
                name="rates_rateanalysisline_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="marketprice",
            index=models.Index(fields=["tenant_id", "price_set"], name="rates_price_tenant_set"),
        ),
        migrations.AddConstraint(
            model_name="marketprice",
            constraint=models.UniqueConstraint(
                fields=("price_set", "resource"), name="rates_marketprice_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__isnull", True), ("price__gte", 0), _connector="OR"),
                name="rates_marketprice_not_negative",
            ),
        ),
        migrations.RunSQL(POLICIES, POLICIES_REVERSE),
        migrations.RunSQL(KEYS, KEYS_REVERSE),
        migrations.RunSQL(RIGHTS, RIGHTS_REVERSE),
    ]
